"users/{{user_name}}/info" = '{"type":"admin"}'
"device/ood01" = "{{ood_doc}}"
"device/zonegate" = "{{zonegate_doc}}"

"system/rbac/model" = """
{{rbac_model}}
"""
"system/rbac/policy" = """
{{rbac_policy}}
"""

"system/verify_hub/key" = "{{verify_hub_key}}"
"services/verify_hub/info" = "{{verify_hub_info}}"
"services/verify_hub/setting" = """
{{verify_hub_setting}}
"""

"services/scheduler/info" = "{{scheduler_info}}"

"services/gateway/info" = "{{gateway_info}}"

"users/{{owner_name}}/apps/buckyos.home_station/info" = """
{
    "app_id":"buckyos.home_station",
    "app_name" : "Home Station",
    "app_description" : "Home Station",
    "vendor_id" : "buckyos",
    "pkg_id" : "home_station",
    "username" : "{{owner_name}}",
    "service_docker_images" : {
        "x86_server" : "buckyos/home_station:latest"
    },
    "data_mount_point" : "/home/data",
    "cache_mount_point" : "/home/cache",
    "local_cache_mount_point" : "/home/local_cache",
    "max_cpu_num" : Some(4),
    "max_cpu_percent" : Some(80),
    "memory_quota" : 1024*1024*1024*1, //1GB
    "host_name" : "home",
    "port" : 20080
}
"""

"nodes/ood01/config" = """
{
        "is_running":true,
        "revision" : 0,
        "kernel" : {
            "verify_hub" : {
                "target_state":"Running",
                "pkg_id":"verify_hub",
                "operations":{
                    "status":{
                        "command":"status",
                        "params":[]
                    },
                    "start":{
                        "command":"start",
                        "params":[]
                    },
                    "stop":{
                        "command":"stop",
                        "params":[]
                    }
                }
            },
            "scheduler" : {
                "target_state":"Running",
                "pkg_id":"scheduler",
                "operations":{
                    "status":{
                        "command":"status",
                        "params":[]
                    },
                    "start":{
                        "command":"start",
                        "params":[]
                    },
                    "stop":{
                        "command":"stop",
                        "params":[]
                    }
                }
            }
        },
        "services":{
        },
        "apps":{
            "app":{
                "target_state":"Running",
                "app_id":"buckyos.home_station",
                "username":"owner_name",
            }
        }
    }
"""

["boot/config"] #  not include jwt related info 
did="did:ens:{{owner_name}}"
oods=["ood01"]
sn="{{web3_bridge}}"

