[package]
name = "ns-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bucky-name-service = {path = "../../kernel/name-service"}
clap = "4.5.4"
sfo-result = "0.1.1"
serde = "1.0.198"
serde_json = "1.0.116"
