[package]
name = "kRPC"
version = "0.2.0"
edition = "2021"
authors = ["BuckyOS DAO","@waterflier"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "*"
tokio = { version = "1", features = ["full"] }
log = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
thiserror = "*"
reqwest = {version = "*", features = ["json", "rustls-tls"]}
jsonwebtoken = "*"