import { expect, test } from '@playwright/test'

test('AI Center exposes the complete catalog and expands multi-currency totals', async ({ page }) => {
  await page.goto('/?scenario=normal&aiccScenario=populated')
  await page.getByTestId('desktop-app-ai-center').click()

  const costCard = page.getByRole('button', { name: /Est\. Cost/ })
  await expect(costCard).toContainText('3 currencies')
  const collapsedCost = await costCard.innerText()
  expect(['USD', 'EUR', 'CNY'].filter((currency) => collapsedCost.includes(currency))).toHaveLength(1)
  await costCard.click()
  await expect(costCard).toContainText('USD')
  await expect(costCard).toContainText('EUR')
  await expect(costCard).toContainText('CNY')

  await page.getByRole('button', { name: 'Providers', exact: true }).click()
  await page.getByRole('button', { name: 'Add Provider' }).click()
  for (const provider of ['OpenAI', 'Anthropic Claude', 'Google Gemini', 'fal', 'OpenRouter', 'MiniMax', 'Moonshot Kimi', 'Z.ai GLM', 'DeepSeek', 'Doubao (Volcengine Ark)', 'Qwen（阿里云百炼）']) {
    await expect(page.getByRole('button').filter({ has: page.getByText(provider, { exact: true }) })).toBeVisible()
  }
  await expect(page.getByRole('button', { name: /Custom Provider/ })).toBeVisible()

  await page.getByRole('button', { name: /Doubao/i }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  const doubaoBaseUrl = page.getByRole('combobox', { name: /^Base URL\s*\*?$/ })
  const doubaoTtsUrl = page.getByRole('combobox', { name: /^Operation Base URL · tts\.unidirectional\s*\*?$/ })
  await expect(page.getByText('Residence / account region', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Set residence / account region' }).click()
  await expect(page.getByText('Residence / account region', { exact: true })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Residence / account region' })).toHaveValue('unknown')
  await page.getByRole('button', { name: 'Use unknown' }).click()
  await expect(page.getByText('Residence / account region', { exact: true })).toHaveCount(0)
  await expect(doubaoBaseUrl).toBeEnabled()
  await expect(doubaoTtsUrl).toBeEnabled()
  await doubaoBaseUrl.fill('https://override.example/v1')
  await expect(doubaoTtsUrl).toHaveValue('https://override.example/v1')
  await page.getByRole('button', { name: 'Base URL: Show configured endpoints' }).click()
  await expect(page.getByRole('option', { name: /Default.*ark\.cn-beijing\.volces\.com/ })).toBeVisible()
  await page.getByRole('option', { name: /Default.*ark\.cn-beijing\.volces\.com/ }).click()
  await expect(doubaoBaseUrl).toHaveValue('https://ark.cn-beijing.volces.com/api/v3')
  await doubaoTtsUrl.fill('https://override.example/tts')
  await page.getByRole('button', { name: 'Operation Base URL · tts.unidirectional: Show configured endpoints' }).click()
  await page.getByRole('option', { name: /Default.*openspeech\.bytedance\.com/ }).click()
  await expect(doubaoTtsUrl).toHaveValue('https://openspeech.bytedance.com/api/v3/tts')
  await page.getByRole('button', { name: 'Previous' }).click()

  await page.getByRole('button', { name: /Qwen/i }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByText('Region', { exact: true })).toHaveCount(0)
  await expect(page.getByText(/^Workspace\s*\*?$/)).toBeVisible()
  await expect(page.getByRole('combobox', { name: /^Base URL\s*\*?$/ })).toHaveValue('https://{workspace}.{region}.maas.aliyuncs.com/compatible-mode/v1')
})
