import { test, expect, type CopyServices } from '../fixtures/nfs-copy'
import type { Page } from '@playwright/test'
import { readFile, stat, lstat, readdir, chmod, unlink, symlink, link, readlink, rename, writeFile, utimes, rm } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'

const hash = async (path: string) => createHash('sha256').update(await readFile(path)).digest('hex')
async function openFiles(page: Page) {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/?scenario=normal&fbData=nfsp')
  await page.getByTestId('desktop-app-files').click()
  const win = page.getByTestId('window-files')
  await expect(win.getByRole('cell', { name: 'Documents', exact: true })).toBeVisible({ timeout: 15000 })
  return win
}
async function go(page: Page, path: string) {
  const win = page.getByTestId('window-files')
  await win.getByTestId('filebrowser').focus()
  await page.keyboard.press('Control+l')
  const input = win.getByRole('textbox', { name: 'path', exact: true })
  await input.fill(path); await input.press('Enter')
  await expect(win.locator('[data-pane="left"]')).toHaveAttribute('data-location', `dfs://${path}`)
  await expect(win.locator('[data-pane="left"]')).toHaveAttribute('data-list-status', 'ready')
  await win.getByTestId('filebrowser').focus()
}
async function copyTo(page: Page, source: string, target: string) {
  const win = page.getByTestId('window-files')
  await win.getByRole('cell', { name: source, exact: true }).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Copy to…', exact: true }).click()
  const dialog = page.getByTestId('target-dialog')
  await dialog.getByRole('textbox', { name: 'Destination' }).fill(target)
  await dialog.getByRole('button', { name: 'Go', exact: true }).click()
  await dialog.getByRole('button', { name: 'Copy here', exact: true }).click()
  await expect(win.getByTestId('copy-task-id')).toBeVisible({ timeout: 15000 })
  return (await win.getByTestId('copy-task-id').textContent())!
}
async function sameBytes(services: CopyServices, source: string, destination: string) {
  expect(await hash(services.path(destination))).toBe(await hash(services.path(source)))
  expect((await stat(services.path(destination))).ino).not.toBe((await stat(services.path(source))).ino)
}

test.use({ actionTimeout: 15000 })
test.describe('FB-04 real copy tasks', () => {
  test.skip(!process.env.FB_COPY_AUTO || !process.env.FB_NFSP_E2E, 'requires the real NFSP + signed TaskMgr/RDB fixture')
  test.describe.configure({ mode: 'default', timeout: 120000 })

  test('browser Copy/Paste to third-level destination, independence, refresh and restart', async ({ page, services: fixture }, testInfo) => {
    const services = fixture!
    const win = await openFiles(page)
    await go(page, '/home/Documents')
    await win.getByRole('cell', { name: 'notes.txt', exact: true }).click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Copy files', exact: true }).click()
    await go(page, '/home/Dest/a/b')
    await page.keyboard.press('Control+v')
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded', { timeout: 30000 })
    const id = (await win.getByTestId('copy-task-id').textContent())!
    const view = await services.terminal(id)
    expect(view.task.creator.user_id).toBe('copy-test-user')
    expect(view.task.schema_id).toBe('nfs.copy/v1')
    await sameBytes(services, 'Documents/notes.txt', 'Dest/a/b/notes.txt')
    const initialEvidence = { taskId: id, sourceSha256: await hash(services.path('Documents/notes.txt')), copySha256: await hash(services.path('Dest/a/b/notes.txt')), sourceInode: (await stat(services.path('Documents/notes.txt'))).ino, copyInode: (await stat(services.path('Dest/a/b/notes.txt'))).ino }
    await expect(win.getByRole('cell', { name: 'notes.txt', exact: true })).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('copy-desktop.png') })
    await page.reload(); await page.getByTestId('desktop-app-files').click()
    await page.getByTestId('copy-tasks').click()
    await expect(page.getByTestId('copy-tasks-dialog')).toContainText(id)
    await services.restartNfs(); await services.restartTasks()
    expect((await services.call('copy_get', { task_id: id })).task.phase).toBe('Terminal')
    await sameBytes(services, 'Documents/notes.txt', 'Dest/a/b/notes.txt')
    await services.write('Documents/notes.txt', 'changed original')
    expect(await readFile(services.path('Dest/a/b/notes.txt'), 'utf8')).toContain('文件内容')
    await unlink(services.path('Documents/notes.txt'))
    expect(await readFile(services.path('Dest/a/b/notes.txt'), 'utf8')).toContain('文件内容')
    await services.write('Documents/notes.txt', 'second original')
    await services.write('Dest/a/b/notes.txt', 'changed copy')
    expect(await readFile(services.path('Documents/notes.txt'), 'utf8')).toBe('second original')
    await unlink(services.path('Dest/a/b/notes.txt'))
    expect(await readFile(services.path('Documents/notes.txt'), 'utf8')).toBe('second original')
    await testInfo.attach('independence-and-persistence.json', { body: JSON.stringify({ ...initialEvidence, verifiedAfterBrowserRefresh: true, verifiedAfterNfsAndTaskManagerRestart: true, sourceAndCopyModificationAndDeletionIndependent: true }, null, 2), contentType: 'application/json' })
  })

  test('same-directory, repeated paste, conflict choices and immutable request replay', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.write('Documents/repeat.txt', 'repeat bytes')
    const win = await openFiles(page); await go(page, '/home/Documents')
    await win.getByRole('cell', { name: 'repeat.txt', exact: true }).click()
    await page.keyboard.press('Control+c'); await page.keyboard.press('Control+v')
    await page.getByTestId('conflict-dialog').getByRole('button', { name: 'Keep both', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
    const first = (await win.getByTestId('copy-task-id').textContent())!
    await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
    await win.getByTestId('filebrowser').focus(); await page.keyboard.press('Control+v')
    await page.getByTestId('conflict-dialog').getByRole('button', { name: 'Keep both', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
    const second = (await win.getByTestId('copy-task-id').textContent())!
    expect(second).not.toBe(first)
    await sameBytes(services, 'Documents/repeat.txt', 'Documents/repeat (2).txt')
    await sameBytes(services, 'Documents/repeat.txt', 'Documents/repeat (3).txt')
    const snapshot = (await services.call('copy_get', { task_id: second })).task
    const repeats = await Promise.all(Array.from({ length: 6 }, () => services.submit(snapshot.input, snapshot.idempotency_key)))
    expect(new Set(repeats)).toEqual(new Set([second]))
    await expect(services.submit({ ...snapshot.input, conflict: 'skip' }, snapshot.idempotency_key)).rejects.toThrow('idempotency')
    expect((await readdir(services.path('Documents'))).filter((name) => name.startsWith('repeat')).length).toBe(3)
    await expect(services.call('copy_get', { task_id: second }, undefined, services.otherToken)).rejects.toThrow('another user')
  })

  test('recursive real filesystem, empty directories, paging, links, metadata and 128 MiB', async ({ page, services: fixture }, testInfo) => {
    const services = fixture!
    await services.directory('Documents/tree/empty')
    await services.directory('Documents/tree/deep/a/b')
    await services.write('Documents/tree/zero', Buffer.alloc(0))
    await services.write('Documents/tree/deep/a/b/数据.bin', Buffer.from(Array.from({ length: 8192 }, (_, i) => i % 256)))
    await services.write(`Documents/tree/${'汉'.repeat(80)}.txt`, 'long UTF-8 name')
    for (let i = 0; i < 230; i++) await services.write(`Documents/tree/page-${String(i).padStart(3, '0')}.txt`, `${i}\n`)
    await services.large('Documents/tree/large.bin', 128)
    await symlink('deep/a/b/数据.bin', services.path('Documents/tree/relative-link'))
    await symlink('missing', services.path('Documents/tree/dangling-link'))
    await symlink(services.path('Documents/notes.txt'), services.path('Documents/tree/absolute-link'))
    await link(services.path('Documents/tree/zero'), services.path('Documents/tree/hard-link'))
    await chmod(services.path('Documents/tree/deep/a/b/数据.bin'), 0o640)
    await utimes(services.path('Documents/tree/deep/a/b/数据.bin'), 1700000000, 1700000123)
    const win = await openFiles(page); await go(page, '/home/Documents')
    const started = Date.now()
    const id = await copyTo(page, 'tree', '/home/Dest/a/b')
    const view = await services.terminal(id)
    expect(view.task.outcome).toBe('Succeeded')
    const items = await services.items(id)
    expect(items.length).toBeGreaterThan(240)
    expect(items.every((item) => item.status === 'success')).toBe(true)
    await sameBytes(services, 'Documents/tree/large.bin', 'Dest/a/b/tree/large.bin')
    await sameBytes(services, 'Documents/tree/deep/a/b/数据.bin', 'Dest/a/b/tree/deep/a/b/数据.bin')
    expect(await readdir(services.path('Dest/a/b/tree/empty'))).toEqual([])
    for (const item of items.filter((item) => item.kind === 'file')) await sameBytes(services, item.source_path.slice(6), item.target_path.slice(6))
    expect((await stat(services.path('Dest/a/b/tree/deep/a/b/数据.bin'))).mode & 0o777).toBe(0o640)
    expect((await stat(services.path('Dest/a/b/tree/deep/a/b/数据.bin'))).mtimeMs).toBe(1700000123000)
    for (const name of ['relative-link', 'dangling-link', 'absolute-link']) {
      expect((await lstat(services.path(`Dest/a/b/tree/${name}`))).isSymbolicLink()).toBe(true)
      expect(await readlink(services.path(`Dest/a/b/tree/${name}`))).toBe(await readlink(services.path(`Documents/tree/${name}`)))
    }
    expect((await stat(services.path('Dest/a/b/tree/hard-link'))).ino).not.toBe((await stat(services.path('Dest/a/b/tree/zero'))).ino)
    expect(await readdir(services.path('Dest/a/b/tree'))).toEqual(await readdir(services.path('Documents/tree')))
    await testInfo.attach('copy-size-and-time.json', { body: JSON.stringify({ bytes: 128 * 1024 * 1024, elapsedMs: Date.now() - started, items: items.length, taskId: id, sha256: await hash(services.path('Dest/a/b/tree/large.bin')) }, null, 2), contentType: 'application/json' })
    await expect(win.getByTestId('batch-results')).toContainText('0 failed', { timeout: 15000 })
    const loadMore = win.getByTestId('batch-results').getByRole('button', { name: 'Load more', exact: true })
    for (let page = 1; page < Math.ceil(items.length / 100); page++) { await loadMore.click(); await expect(win.getByTestId('batch-results').locator('li[data-status]')).toHaveCount(Math.min((page + 1) * 100, items.length)) }
    await expect(loadMore).toHaveCount(0)
  })

  test('real read denial, partial directory retry reuses verified copies, and read-only target', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.write('Documents/partial/A.txt', 'success A')
    await services.write('Documents/partial/C.txt', 'denied C')
    await chmod(services.path('Documents/partial/C.txt'), 0)
    const win = await openFiles(page); await go(page, '/home/Documents')
    const id = await copyTo(page, 'partial', '/home/Pictures')
    const failed = await services.terminal(id)
    expect(failed.task.outcome).toBe('Failed')
    expect(failed.items.find((item: any) => item.source_path.endsWith('/C.txt')).error.code).toBe('PERMISSION_DENIED')
    const a = await stat(services.path('Pictures/partial/A.txt'))
    expect(failed.items.find((item: any) => item.source_path.endsWith('/partial')).status).toBe('failed')
    await expect(win.getByTestId('batch-results')).toContainText('directory is partially copied')
    await chmod(services.path('Documents/partial/C.txt'), 0o644)
    await win.getByTestId('batch-results').getByRole('button', { name: 'Retry failed items' }).click()
    await expect.poll(async () => win.getByTestId('copy-task-id').textContent()).not.toBe(id)
    const retry = (await win.getByTestId('copy-task-id').textContent())!
    const done = await services.terminal(retry)
    expect(done.task.retry_of).toBe(id); expect(done.task.outcome).toBe('Succeeded')
    expect((await stat(services.path('Pictures/partial/A.txt'))).ino).toBe(a.ino)
    await sameBytes(services, 'Documents/partial/C.txt', 'Pictures/partial/C.txt')
    expect((await services.call('copy_get', { task_id: id })).task).toEqual(failed.task)
    await services.directory('readonly')
    await chmod(services.path('readonly'), 0o555)
    const readonly = await services.submit(await services.input(['Documents/notes.txt'], 'readonly'))
    const denied = await services.terminal(readonly)
    expect(denied.items[0].error.code).toBe('PERMISSION_DENIED')
    expect(await readdir(services.path('readonly'))).toEqual([])
  })

  test('response loss, concurrent replay and restart after durable file commit', async ({ page, services: fixture }, testInfo) => {
    const services = fixture!
    await services.write('Documents/recovery.txt', 'recover exactly once')
    const win = await openFiles(page); await go(page, '/home/Documents')
    let lostId = ''
    let requests = 0
    await page.route('**/nfs/v1/copy_submit', async (route) => {
      if (requests++ === 0) { const response = await route.fetch(); lostId = (await response.json()).result.task_id; await route.abort('failed') } else await route.continue()
    })
    const id = await copyTo(page, 'recovery.txt', '/home/Pictures')
    expect(id).toBe(lostId)
    await services.terminal(id)
    const task = (await services.call('copy_get', { task_id: id })).task
    const ids = await Promise.all(Array.from({ length: 8 }, () => services.submit(task.input, task.idempotency_key)))
    expect(new Set(ids)).toEqual(new Set([id]))
    expect((await readdir(services.path('Pictures'))).filter((name) => name.startsWith('recovery'))).toEqual(['recovery.txt'])
    await page.unroute('**/nfs/v1/copy_submit')
    await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
    await services.write('Documents/crash.txt', 'committed before progress')
    await services.restartNfs({ NFS_COPY_TEST_FAULT: 'after-commit' })
    await go(page, '/home/Pictures'); await go(page, '/home/Documents')
    const pending = copyTo(page, 'crash.txt', '/home/Pictures')
    await expect.poll(async () => stat(`${services.root}/nfs/copy-fault-fired`).then(() => true).catch(() => false), { timeout: 30000 }).toBe(true)
    const identity = await stat(services.path('Pictures/crash.txt'))
    await services.restartNfs()
    const recoveredId = await pending
    const recovered = await services.terminal(recoveredId)
    expect(recovered.task.outcome).toBe('Succeeded')
    expect((await stat(services.path('Pictures/crash.txt'))).ino).toBe(identity.ino)
    expect((await readdir(services.path('Pictures'))).filter((name) => name.includes('crash') || name.startsWith('.bucky-copy-'))).toEqual(['crash.txt'])
    await sameBytes(services, 'Documents/crash.txt', 'Pictures/crash.txt')
    await testInfo.attach('recovery.json', { body: JSON.stringify({ responseLossTask: id, recoveredTask: recoveredId, inodeBeforeRecovery: identity.ino, inodeAfterRecovery: (await stat(services.path('Pictures/crash.txt'))).ino, items: recovered.items }, null, 2), contentType: 'application/json' })
  })

  test('cancel through TaskMgr keeps committed children and cleans temporary files', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.write('Documents/cancel-tree/A.txt', 'committed A')
    await services.large('Documents/cancel-tree/B.bin', 128)
    await services.write('Documents/cancel-tree/C.txt', 'pending C')
    await services.restartNfs({ NFS_COPY_TEST_SLOW: '1' })
    const win = await openFiles(page); await go(page, '/home/Documents')
    const id = await copyTo(page, 'cancel-tree', '/home/Pictures')
    await expect.poll(async () => stat(services.path('Pictures/cancel-tree/A.txt')).then(() => true).catch(() => false)).toBe(true)
    await win.getByTestId('batch-results').getByRole('button', { name: 'Cancel remaining', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('Cancelling…')
    const view = await services.terminal(id)
    expect(view.task.outcome).toBe('Canceled')
    const items = await services.items(id)
    expect(items.some((item) => item.status === 'success')).toBe(true)
    expect(items.some((item) => item.status === 'cancelled')).toBe(true)
    expect((await readdir(services.path('Pictures/cancel-tree'))).some((name) => name.startsWith('.bucky-copy-'))).toBe(false)
    await sameBytes(services, 'Documents/cancel-tree/A.txt', 'Pictures/cancel-tree/A.txt')
    await services.restartNfs()
  })

  test('Copy reads modified content at execution, rejects replacements and detects mid-copy changes', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.write('Documents/change.txt', 'before copy')
    const win = await openFiles(page); await go(page, '/home/Documents')
    await win.getByRole('cell', { name: 'change.txt', exact: true }).click()
    await expect(win.getByRole('button', { name: 'Copy files', exact: true })).toBeVisible()
    await page.keyboard.press('Control+c')
    await expect(win.getByRole('button', { name: 'Paste', exact: true })).toBeVisible()
    await services.write('Documents/change.txt', 'changed before paste')
    await go(page, '/home/Pictures'); await page.keyboard.press('Control+v')
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
    expect(await readFile(services.path('Pictures/change.txt'), 'utf8')).toBe('changed before paste')
    await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
    await go(page, '/home/Documents')
    await win.getByRole('cell', { name: 'change.txt', exact: true }).click()
    await expect(win.getByRole('button', { name: 'Copy files', exact: true })).toBeVisible()
    await page.keyboard.press('Control+c')
    await expect(win.getByRole('button', { name: 'Paste', exact: true })).toBeVisible()
    await rename(services.path('Documents/change.txt'), services.path('Documents/change-old.txt'))
    await services.write('Documents/change.txt', 'replacement must not be copied')
    await go(page, '/home/Dest/a/b'); await page.keyboard.press('Control+v')
    await expect(win.getByTestId('batch-results')).toContainText('1 failed')
    expect(await stat(services.path('Dest/a/b/change.txt')).catch(() => null)).toBeNull()
    await services.large('Documents/changing.bin', 128)
    await services.restartNfs({ NFS_COPY_TEST_SLOW: '1' })
    const id = await services.submit(await services.input(['Documents/changing.bin'], 'Pictures'))
    await expect.poll(async () => (await readdir(services.path('Pictures'))).some((name) => name.startsWith('.bucky-copy-'))).toBe(true)
    await writeFile(services.path('Documents/changing.bin'), 'changed while reading')
    const changed = await services.terminal(id)
    expect(changed.task.outcome).toBe('Failed')
    expect(changed.items[0].error.code).toBe('STALE')
    expect(await stat(services.path('Pictures/changing.bin')).catch(() => null)).toBeNull()
    expect((await readdir(services.path('Pictures'))).some((name) => name.startsWith('.bucky-copy-'))).toBe(false)
    await services.restartNfs()
  })

  test('file/directory conflicts, batch decisions, skip, cancel and descendant rejection', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.write('Documents/conflicts/A.txt', 'new A')
    await services.write('Documents/conflicts/B.txt', 'new B')
    await services.directory('Documents/conflicts/C.dir')
    await services.directory('Documents/conflicts/D.dir')
    await services.write('Documents/conflicts/E.txt', 'file with directory name')
    await services.directory('Pictures/conflicts/D.dir')
    await services.directory('Pictures/conflicts/E.txt')
    await services.write('Pictures/conflicts/A.txt', 'existing A')
    await services.write('Pictures/conflicts/B.txt', 'existing B')
    await services.write('Pictures/conflicts/C.dir', 'existing file with directory name')
    const win = await openFiles(page); await go(page, '/home/Documents/conflicts')
    for (const name of ['A.txt', 'B.txt', 'C.dir', 'D.dir', 'E.txt']) await win.getByRole('checkbox', { name: `Select ${name}`, exact: true }).check()
    await win.getByTestId('filebrowser').focus(); await page.keyboard.press('Control+c')
    await go(page, '/home/Pictures/conflicts'); await page.keyboard.press('Control+v')
    const conflict = page.getByTestId('conflict-dialog')
    await conflict.getByRole('checkbox').check()
    await conflict.getByRole('button', { name: 'Keep both', exact: true }).click()
    await expect(conflict).toContainText('C.dir')
    await conflict.getByRole('button', { name: 'Skip', exact: true }).click()
    await expect(conflict).toContainText('D.dir')
    await conflict.getByRole('button', { name: 'Keep both', exact: true }).click()
    await expect(conflict).toContainText('E.txt')
    await conflict.getByRole('button', { name: 'Skip', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('3 succeeded · 0 failed · 2 skipped')
    expect((await stat(services.path('Pictures/conflicts/D.dir (2)'))).isDirectory()).toBe(true)
    expect((await stat(services.path('Pictures/conflicts/E.txt'))).isDirectory()).toBe(true)
    expect(await readFile(services.path('Pictures/conflicts/A.txt'), 'utf8')).toBe('existing A')
    expect(await readFile(services.path('Pictures/conflicts/B.txt'), 'utf8')).toBe('existing B')
    await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
    await win.getByTestId('filebrowser').focus(); await page.keyboard.press('Control+v')
    await conflict.getByRole('button', { name: 'Cancel remaining', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('5 cancelled')
    const descendant = await services.submit(await services.input(['Documents/conflicts'], 'Documents/conflicts/C.dir'))
    expect((await services.terminal(descendant)).task.outcome).toBe('Failed')
    expect(await readdir(services.path('Documents/conflicts/C.dir'))).toEqual([])
  })

  test('special files fail without reading and virtual bindings are reported as skipped', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.write('Documents/virtual/normal.txt', 'normal')
    execFileSync('mkfifo', [services.path('Documents/virtual/pipe')])
    const parent = (await services.call('stat', {}, '/home/Documents/virtual')).ref
    const source = (await services.call('stat', {}, '/home/Documents/notes.txt')).ref
    const response = await fetch('http://127.0.0.1:3262/nfs/v1/bind_ref', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ session: services.session, seq: 1, args: { parent_ref: parent, name: 'virtual-binding', target_ref: source } }) })
    expect((await response.json()).ok).toBe(true)
    await openFiles(page); await go(page, '/home/Documents')
    const id = await copyTo(page, 'virtual', '/home/Pictures')
    const view = await services.terminal(id)
    expect(view.task.outcome).toBe('Failed')
    const rows = await services.items(id)
    expect(rows.find((row) => row.source_path.endsWith('/pipe')).error.code).toBe('UNSUPPORTED')
    expect(rows.find((row) => row.source_path.endsWith('/virtual-binding')).status).toBe('skipped')
    expect(await readdir(services.path('Pictures/virtual'))).toEqual(['normal.txt'])
  })

  test('copy to other pane, modifier drop, toolbar, native text shortcuts and new selection during copying', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.write('Documents/pane.txt', 'other pane bytes')
    await services.write('Documents/drag.txt', 'drag bytes')
    await services.large('Documents/slow-selection.bin', 128)
    const win = await openFiles(page)
    await win.getByRole('button', { name: 'Pictures', exact: true }).last().click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Send to Right', exact: true }).click()
    const left = win.locator('[data-pane="left"]')
    const right = win.locator('[data-pane="right"]')
    await left.getByRole('cell', { name: 'Documents', exact: true }).dblclick()
    await left.getByRole('cell', { name: 'pane.txt', exact: true }).click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Copy to other pane', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
    await sameBytes(services, 'Documents/pane.txt', 'Pictures/pane.txt')
    await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
    const transfer = await page.evaluateHandle(() => new DataTransfer())
    const row = left.getByRole('row').filter({ has: page.getByRole('cell', { name: 'drag.txt', exact: true }) })
    await row.dispatchEvent('dragstart', { dataTransfer: transfer })
    await right.dispatchEvent('drop', { dataTransfer: transfer, ctrlKey: true })
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
    await sameBytes(services, 'Documents/drag.txt', 'Pictures/drag.txt')
    await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
    await left.getByRole('cell', { name: 'pane.txt', exact: true }).click()
    await left.getByRole('button', { name: 'Copy files', exact: true }).click()
    await left.getByRole('button', { name: 'Copy to', exact: true }).click()
    const target = page.getByTestId('target-dialog')
    const input = target.getByRole('textbox', { name: 'Destination' })
    await input.fill('/home/Dest/a/b'); await input.press('Control+a'); await input.press('Control+c'); await input.press('Control+v')
    await expect(input).toHaveValue('/home/Dest/a/b')
    await target.getByRole('button', { name: 'Cancel', exact: true }).click()
    await services.restartNfs({ NFS_COPY_TEST_SLOW: '1' })
    await left.getByRole('cell', { name: 'slow-selection.bin', exact: true }).click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Copy to other pane', exact: true }).click()
    await expect(win.getByTestId('copy-task-id')).toBeVisible()
    await left.getByRole('button', { name: 'New tab', exact: true }).click()
    await left.getByRole('cell', { name: 'Pictures', exact: true }).dblclick()
    await left.getByRole('cell', { name: 'pane.txt', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded', { timeout: 30000 })
    await expect(left.getByText('Selected: pane.txt', { exact: true })).toBeVisible()
    await sameBytes(services, 'Documents/slow-selection.bin', 'Pictures/slow-selection.bin')
    await services.restartNfs()
  })

  test('375px mobile shared copy menu writes an independent real file', async ({ browser, services: fixture }, testInfo) => {
    const services = fixture!
    await services.write('Documents/mobile.txt', 'mobile bytes')
    const context = await browser.newContext({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true, extraHTTPHeaders: { Authorization: `Bearer ${services.token}` } })
    const page = await context.newPage()
    try {
      await page.goto('/?scenario=normal&fbData=nfsp')
      await page.getByRole('button', { name: 'Files', exact: true }).tap()
      const files = page.getByTestId('filebrowser')
      await files.getByRole('button', { name: /Documents/ }).tap()
      const row = files.getByRole('button', { name: /mobile.txt/ }).first()
      await row.getByRole('button', { name: 'More actions', exact: true }).tap()
      await page.getByRole('button', { name: 'Copy to…', exact: true }).tap()
      const target = page.getByTestId('target-dialog')
      await target.getByRole('textbox', { name: 'Destination' }).fill('/home/Dest/a/b')
      await target.getByRole('button', { name: 'Go', exact: true }).tap()
      await target.getByRole('button', { name: 'Copy here', exact: true }).tap()
      await expect(files.getByTestId('batch-results')).toContainText('1 succeeded', { timeout: 30000 })
      await sameBytes(services, 'Documents/mobile.txt', 'Dest/a/b/mobile.txt')
      await page.screenshot({ path: testInfo.outputPath('copy-mobile-375.png') })
    } finally { await context.close() }
  })

  test('collection entity references copy the real source, while groups and named objects are unsupported', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.write('Documents/member.txt', 'member content')
    const win = await openFiles(page)
    await win.locator('aside').first().getByRole('button', { name: 'New collection…' }).click()
    const dialog = page.getByTestId('name-prompt-dialog')
    await dialog.getByRole('textbox').fill('Copy collection')
    await dialog.getByRole('button', { name: 'Create', exact: true }).click()
    await expect(dialog).toHaveCount(0)
    await expect(win.getByText('Collection: Copy collection')).toBeVisible()
    await go(page, '/home/Documents')
    await win.getByRole('cell', { name: 'member.txt', exact: true }).click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Add to Collection', exact: true }).click()
    await page.getByRole('menuitem', { name: 'Copy collection', exact: true }).click()
    await win.locator('aside').first().getByRole('button', { name: /^Copy collection(?: \d+)?$/ }).click()
    await expect(win.getByRole('cell', { name: 'member.txt', exact: true })).toBeVisible()
    const id = await copyTo(page, 'member.txt', '/home/Pictures')
    expect((await services.terminal(id)).task.outcome).toBe('Succeeded')
    await sameBytes(services, 'Documents/member.txt', 'Pictures/member.txt')
    await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
    await win.getByRole('cell', { name: 'member.txt', exact: true }).click()
    await win.getByTestId('filebrowser').focus(); await page.keyboard.press('Control+c')
    await rename(services.path('Documents/member.txt'), services.path('Documents/member-old.txt'))
    await services.write('Documents/member.txt', 'replacement member')
    await go(page, '/home/Dest/a/b'); await page.keyboard.press('Control+v')
    await expect(win.getByTestId('batch-results')).toContainText('1 failed')
    expect(await stat(services.path('Dest/a/b/member.txt')).catch(() => null)).toBeNull()
    await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
    await win.locator('aside').first().getByRole('button', { name: /^Copy collection(?: \d+)?$/ }).click()
    await win.getByRole('cell', { name: 'member.txt', exact: true }).click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Remove from collection', exact: true }).click()
    await page.getByTestId('delete-dialog').getByRole('button', { name: 'Remove from collection', exact: true }).click()
    await expect(win.getByRole('cell', { name: 'member.txt', exact: true })).toHaveCount(0)
    expect(await readFile(services.path('Documents/member.txt'), 'utf8')).toBe('replacement member')
    expect(await readFile(services.path('Documents/member-old.txt'), 'utf8')).toBe('member content')
    await win.getByRole('button', { name: 'More actions', exact: true }).click()
    await page.getByRole('menuitem', { name: 'New group…', exact: true }).click()
    await dialog.getByRole('textbox').fill('Not a folder')
    await dialog.getByRole('button', { name: 'Create', exact: true }).click()
    await win.getByRole('cell', { name: 'Not a folder', exact: true }).click({ button: 'right' })
    await expect(page.getByRole('menuitem', { name: /^Copy files/ })).toHaveAttribute('aria-disabled', 'true')
    await page.keyboard.press('Escape')
    const input = await services.input(['Documents/member.txt'], 'Pictures')
    const object = await services.submit({ ...input, sources: [{ name: 'object', source_path: 'obj://test', source_ref: { type: 'object', obj_id: 'sha256:aaaaaaaa' } }] })
    expect((await services.terminal(object)).items[0].error.code).toBe('UNSUPPORTED')
  })

  test('unfinished copy resumes the same task after process death and concurrent initial submissions', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.large('Documents/interrupted.bin', 64)
    await services.restartNfs({ NFS_COPY_TEST_SLOW: '1' })
    const win = await openFiles(page); await go(page, '/home/Documents')
    const id = await copyTo(page, 'interrupted.bin', '/home/Pictures')
    await expect.poll(async () => (await readdir(services.path('Pictures'))).some((name) => name.startsWith('.bucky-copy-'))).toBe(true)
    await services.restartNfs()
    const view = await services.terminal(id)
    expect(view.task.outcome).toBe('Succeeded')
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded', { timeout: 15000 })
    await sameBytes(services, 'Documents/interrupted.bin', 'Pictures/interrupted.bin')
    const input = await services.input(['Documents/interrupted.bin'], 'Dest/a/b')
    const key = crypto.randomUUID()
    const ids = await Promise.all(Array.from({ length: 8 }, () => services.submit(input, key)))
    expect(new Set(ids).size).toBe(1)
    expect((await services.terminal(ids[0])).task.outcome).toBe('Succeeded')
    expect((await readdir(services.path('Dest/a/b'))).filter((name) => name.startsWith('interrupted'))).toEqual(['interrupted.bin'])
  })

  test('mixed success, skipped conflict and filesystem denial retry without duplicate success', async ({ page, services: fixture }) => {
    const services = fixture!
    for (const name of ['A.txt', 'B.txt', 'C.txt']) await services.write(`Documents/mixed/${name}`, name)
    await services.write('Pictures/mixed/B.txt', 'keep existing B')
    await chmod(services.path('Documents/mixed/C.txt'), 0)
    const win = await openFiles(page); await go(page, '/home/Documents/mixed')
    for (const name of ['A.txt', 'B.txt', 'C.txt']) await win.getByRole('checkbox', { name: `Select ${name}`, exact: true }).check()
    await win.getByTestId('filebrowser').focus(); await page.keyboard.press('Control+c')
    await go(page, '/home/Pictures/mixed'); await page.keyboard.press('Control+v')
    await page.getByTestId('conflict-dialog').getByRole('button', { name: 'Skip', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded · 1 failed · 1 skipped')
    const original = (await win.getByTestId('copy-task-id').textContent())!
    const before = await stat(services.path('Pictures/mixed/A.txt'))
    await chmod(services.path('Documents/mixed/C.txt'), 0o644)
    await win.getByTestId('batch-results').getByRole('button', { name: 'Retry failed items' }).click()
    await expect(win.getByTestId('batch-results')).toContainText('2 succeeded · 0 failed · 1 skipped')
    const retry = (await win.getByTestId('copy-task-id').textContent())!
    expect((await services.call('copy_get', { task_id: retry })).task.retry_of).toBe(original)
    expect((await services.call('copy_get', { task_id: original })).task.outcome).toBe('Failed')
    expect((await stat(services.path('Pictures/mixed/A.txt'))).ino).toBe(before.ino)
    expect(await readFile(services.path('Pictures/mixed/B.txt'), 'utf8')).toBe('keep existing B')
    await sameBytes(services, 'Documents/mixed/C.txt', 'Pictures/mixed/C.txt')
  })

  test('all submit responses lost, manual retry and page refresh retain the same running task', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.large('Documents/lost-all.bin', 256)
    await services.restartNfs({ NFS_COPY_TEST_SLOW: '1' })
    const win = await openFiles(page); await go(page, '/home/Documents')
    const submissions: { taskId: string; key: string; input: unknown }[] = []
    await page.route('**/nfs/v1/copy_submit', async (route) => {
      const body = route.request().postDataJSON()
      const response = await route.fetch()
      submissions.push({ taskId: (await response.json()).result.task_id, key: body.args.idempotency_key, input: body.args.input })
      await route.abort('failed')
    })
    await win.getByRole('cell', { name: 'lost-all.bin', exact: true }).click()
    await win.getByRole('button', { name: 'Copy files', exact: true }).click()
    await go(page, '/home/Dest/a/b'); await win.getByRole('button', { name: 'Paste', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('1 failed')
    expect(submissions.length).toBe(3)
    expect(new Set(submissions.map((item) => JSON.stringify(item))).size).toBe(1)
    await page.unroute('**/nfs/v1/copy_submit')
    await win.getByTestId('batch-results').getByRole('button', { name: 'Retry failed items' }).click()
    await expect(win.getByTestId('copy-task-id')).toHaveText(submissions[0].taskId)
    expect((await services.call('copy_get', { task_id: submissions[0].taskId })).task.phase).not.toBe('Terminal')
    await page.reload(); await page.getByTestId('desktop-app-files').click()
    await win.getByTestId('copy-tasks').click()
    const row = page.getByTestId('copy-tasks-dialog').locator('div.border-b').filter({ hasText: submissions[0].taskId })
    await row.getByRole('button', { name: 'View task', exact: true }).click()
    await expect(win.getByTestId('copy-task-id')).toHaveText(submissions[0].taskId)
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded', { timeout: 30000 })
    await sameBytes(services, 'Documents/lost-all.bin', 'Dest/a/b/lost-all.bin')
    expect((await readdir(services.path('Dest/a/b'))).filter((name) => name.startsWith('lost-all'))).toEqual(['lost-all.bin'])
    await services.restartNfs()
  })

  test('ambiguous committed target is reported for reconciliation without creating another copy', async ({ services: fixture }, testInfo) => {
    const services = fixture!
    await services.write('Documents/audit.txt', 'original committed copy')
    await rm(`${services.root}/nfs/copy-fault-fired`, { force: true })
    await services.restartNfs({ NFS_COPY_TEST_FAULT: 'after-commit' })
    const id = await services.submit(await services.input(['Documents/audit.txt'], 'Pictures'))
    await expect.poll(async () => stat(`${services.root}/nfs/copy-fault-fired`).then(() => true).catch(() => false)).toBe(true)
    await rename(services.path('Pictures/audit.txt'), services.path('Pictures/audit-moved.txt'))
    await services.write('Pictures/audit.txt', 'unrelated replacement')
    await services.restartNfs()
    const view = await services.terminal(id)
    expect(view.task.outcome).toBe('Failed')
    expect(view.items[0].error.message).toContain('manual reconciliation required')
    expect(await readFile(services.path('Pictures/audit.txt'), 'utf8')).toBe('unrelated replacement')
    expect(await readFile(services.path('Pictures/audit-moved.txt'), 'utf8')).toBe('original committed copy')
    expect((await readdir(services.path('Pictures'))).filter((name) => name.startsWith('audit'))).toEqual(['audit-moved.txt', 'audit.txt'])
    await testInfo.attach('ambiguous-recovery.json', { body: JSON.stringify(view, null, 2), contentType: 'application/json' })
  })

  test('source moved before Paste and destination removed during copying cannot report success', async ({ services: fixture }) => {
    const services = fixture!
    await services.write('Documents/moved.txt', 'moved original')
    const input = await services.input(['Documents/moved.txt'], 'Pictures')
    await rename(services.path('Documents/moved.txt'), services.path('Documents/moved-away.txt'))
    const moved = await services.terminal(await services.submit(input))
    expect(moved.task.outcome).toBe('Failed')
    expect(moved.items[0].error.code).toBe('STALE')
    expect(await stat(services.path('Pictures/moved.txt')).catch(() => null)).toBeNull()
    await services.large('Documents/target-gone.bin', 64)
    await services.directory('disappearing')
    await services.restartNfs({ NFS_COPY_TEST_SLOW: '1' })
    const id = await services.submit(await services.input(['Documents/target-gone.bin'], 'disappearing'))
    await expect.poll(async () => (await readdir(services.path('disappearing'))).some((name) => name.startsWith('.bucky-copy-'))).toBe(true)
    await rm(services.path('disappearing'), { recursive: true })
    const gone = await services.terminal(id)
    expect(gone.task.outcome).toBe('Failed')
    expect(gone.summary.success).toBe(0)
    expect(await stat(services.path('disappearing')).catch(() => null)).toBeNull()
    await services.restartNfs()
  })

  test('copy destination browser creates a deep folder and reuses breadcrumb and recent targets', async ({ page, services: fixture }) => {
    const services = fixture!
    await services.write('Documents/browse.txt', 'destination browser')
    const win = await openFiles(page); await go(page, '/home/Documents')
    await win.getByRole('cell', { name: 'browse.txt', exact: true }).click()
    await win.getByRole('button', { name: 'Copy to', exact: true }).click()
    const target = page.getByTestId('target-dialog')
    await target.getByRole('textbox', { name: 'Destination' }).fill('/home/Dest/a')
    await target.getByRole('button', { name: 'Go', exact: true }).click()
    await target.getByRole('button', { name: 'New folder here', exact: true }).click()
    const prompt = page.getByTestId('name-prompt-dialog')
    await prompt.getByRole('textbox').fill('copy-created')
    await prompt.getByRole('button', { name: 'Create', exact: true }).click()
    await target.getByRole('button', { name: '📁 copy-created', exact: true }).click()
    await target.getByRole('button', { name: 'a /', exact: true }).click()
    await target.getByRole('button', { name: '📁 copy-created', exact: true }).click()
    await target.getByRole('button', { name: 'Copy here', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
    await sameBytes(services, 'Documents/browse.txt', 'Dest/a/copy-created/browse.txt')
    await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
    await win.getByRole('button', { name: 'Copy to', exact: true }).click()
    await target.getByText('Recent destinations', { exact: true }).click()
    await target.getByRole('button', { name: '/home/Dest/a/copy-created', exact: true }).click()
    await target.getByRole('button', { name: 'Copy here', exact: true }).click()
    await page.getByTestId('conflict-dialog').getByRole('button', { name: 'Keep both', exact: true }).click()
    await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
    await sameBytes(services, 'Documents/browse.txt', 'Dest/a/copy-created/browse (2).txt')
  })
})
