import { expect, test, type Page } from '@playwright/test'

async function openFiles(page: Page, extra = '') {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(`/?scenario=normal&fbData=mock${extra}`)
  await page.getByTestId('desktop-app-files').click()
  const win = page.getByTestId('window-files')
  await expect(win.getByRole('cell', { name: 'Documents', exact: true })).toBeVisible()
  return win
}
async function documents(page: Page) {
  const win = page.getByTestId('window-files')
  await win.locator('aside').first().getByRole('button', { name: 'Documents', exact: true }).click()
  await expect(win.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true })).toBeVisible()
  return win
}
async function fixture(page: Page, entries: { id: string; name: string; path: string; kind?: string; sizeBytes?: number }[]) {
  await page.evaluate(async (entries) => {
    const data = await import('/src/app/filebrowser/mock/' + 'data.ts')
    const reader = await import('/src/app/filebrowser/data/' + 'mockReader.ts')
    for (const entry of entries) data.mockAddEntry({ kind: 'document', modifiedAt: '2026-09-07T00:00:00Z', ...entry })
    new Set(entries.map((entry) => entry.path.slice(0, entry.path.lastIndexOf('/')))).forEach((path) => reader.invalidateMockPath(path))
  }, entries)
}

test('FB-01: tabs isolate selection and search; history restores the search', async ({ page }) => {
  const win = await openFiles(page)
  await documents(page)
  await win.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true }).click()
  await win.getByRole('button', { name: 'Pictures', exact: true }).last().click()
  await expect(win.getByText('Selected: Kyoto Trip Plan.md')).toHaveCount(0)
  await page.keyboard.press('F2')
  await expect(page.getByTestId('name-prompt-dialog')).toHaveCount(0)
  await win.getByRole('button', { name: 'Documents', exact: true }).last().click()
  await expect(win.getByText('Selected: Kyoto Trip Plan.md')).toBeVisible()
  await win.getByRole('button', { name: 'Search', exact: true }).click()
  await win.getByPlaceholder(/Search across files/).fill('trip')
  await expect(win.getByTestId('search-hit').first()).toBeVisible()
  await win.locator('aside').first().getByRole('button', { name: 'Downloads', exact: true }).click()
  await expect(win.getByTestId('search-hit')).toHaveCount(0)
  await win.getByRole('button', { name: 'back', exact: true }).click()
  await expect(win.getByPlaceholder(/Search across files/)).toHaveValue('trip')
  await expect(win.getByTestId('search-hit').first()).toBeVisible()
})

test('FB-01/02: a slow move preserves a new selection in another tab', async ({ page }) => {
  const win = await openFiles(page, '&fbSlowOps=1')
  await documents(page)
  await win.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true }).click()
  await page.keyboard.press('Control+x')
  await win.getByRole('button', { name: 'Pictures', exact: true }).last().click()
  await page.keyboard.press('Control+v')
  await expect(win.getByTestId('batch-results')).toBeVisible()
  await win.getByRole('button', { name: 'Documents', exact: true }).last().click()
  await win.getByRole('cell', { name: '2026 Q1 Review.docx', exact: true }).click()
  await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
  await expect(win.getByText('Selected: 2026 Q1 Review.docx')).toBeVisible()
  await expect(win.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true })).toHaveCount(0)
  await win.getByRole('button', { name: 'Pictures', exact: true }).last().click()
  await expect(win.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true })).toBeVisible()
})

test('FB-02/04: partial move reports each item and retains pending clipboard entries', async ({ page }) => {
  const win = await openFiles(page)
  await fixture(page, [
    { id: 'review-a', name: 'A-ok.txt', path: '/home/Documents/A-ok.txt' },
    { id: 'review-b', name: 'B-conflict.txt', path: '/home/Documents/B-conflict.txt' },
    { id: 'review-c', name: 'denied-C.txt', path: '/home/Documents/denied-C.txt' },
    { id: 'review-existing', name: 'B-conflict.txt', path: '/home/Pictures/B-conflict.txt' },
  ])
  await documents(page)
  for (const name of ['A-ok.txt', 'B-conflict.txt', 'denied-C.txt']) await win.getByRole('checkbox', { name: `Select ${name}`, exact: true }).check()
  await win.locator('[data-pane="left"]').click({ position: { x: 10, y: 10 } })
  await page.keyboard.press('Control+x')
  await win.getByRole('button', { name: 'Pictures', exact: true }).last().click()
  await page.keyboard.press('Control+v')
  await expect(page.getByTestId('conflict-dialog')).toContainText('B-conflict.txt')
  await page.getByTestId('conflict-dialog').getByRole('button', { name: 'Skip', exact: true }).click()
  const results = win.getByTestId('batch-results')
  await expect(results).toContainText('1 succeeded · 1 failed · 1 skipped · 0 cancelled')
  await expect(win.getByRole('cell', { name: 'A-ok.txt', exact: true })).toBeVisible()
  await results.getByRole('button', { name: 'Close', exact: true }).click()
  await win.getByRole('button', { name: 'More actions', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Paste', exact: true }).click()
  await page.getByTestId('conflict-dialog').getByRole('button', { name: 'Keep both', exact: true }).click()
  await expect(results).toContainText('2/2')
  await expect(results).toContainText('1 succeeded · 1 failed')
  await expect(win.getByRole('cell', { name: 'B-conflict (2).txt', exact: true })).toBeVisible()
  await expect(win.getByRole('cell', { name: 'A-ok.txt', exact: true })).toHaveCount(1)
})

test('FB-04/05: deep destination, self-move prevention and in-app deletion confirmation', async ({ page }) => {
  const win = await openFiles(page)
  await fixture(page, [
    { id: 'deep-1', name: 'one', path: '/home/Downloads/one', kind: 'folder' },
    { id: 'deep-2', name: 'two', path: '/home/Downloads/one/two', kind: 'folder' },
    { id: 'deep-3', name: 'three', path: '/home/Downloads/one/two/three', kind: 'folder' },
  ])
  await documents(page)
  await win.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true }).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Move to', exact: true }).click()
  const dialog = page.getByTestId('target-dialog')
  await dialog.getByRole('textbox', { name: 'Destination' }).fill('/home/Downloads')
  await dialog.getByRole('button', { name: 'Go', exact: true }).click()
  for (const name of ['one', 'two', 'three']) await dialog.getByRole('button', { name: new RegExp(name) }).last().click()
  await dialog.getByRole('button', { name: 'Move here' }).click()
  await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
  await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
  await win.locator('aside').first().getByRole('button', { name: 'Downloads', exact: true }).click()
  await win.getByRole('cell', { name: 'one', exact: true }).click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Move to', exact: true }).click()
  await dialog.getByRole('button', { name: /one/ }).last().click()
  await expect(dialog.getByRole('button', { name: 'Move here' })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await win.getByRole('cell', { name: 'one', exact: true }).click()
  await page.keyboard.press('Delete')
  const deletion = page.getByTestId('delete-dialog')
  await expect(deletion).toContainText('All contents')
  await deletion.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(win.getByRole('cell', { name: 'one', exact: true })).toBeVisible()
})

test('FB-06: scope changes, direct opening and reveal at index 5000', async ({ page }) => {
  const win = await openFiles(page)
  await documents(page)
  await win.getByRole('button', { name: 'Search', exact: true }).click()
  await win.getByPlaceholder(/Search across files/).fill('trip')
  await expect(win.getByTestId('search-hit').first()).toBeVisible()
  const localCount = await win.getByTestId('search-hit').count()
  await win.getByRole('combobox', { name: 'Search in' }).selectOption('all')
  await expect.poll(() => win.getByTestId('search-hit').count()).toBeGreaterThan(localCount)
  await win.getByPlaceholder(/Search across files/).fill('stress-index:5000')
  await expect(win.getByTestId('search-hit')).toHaveCount(1)
  const targetId = await win.getByTestId('search-hit').getAttribute('data-entry-id')
  await win.getByTestId('search-hit').click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Jump to original location', exact: true }).click()
  const row = win.locator(`[data-entry-id="${targetId}"]`)
  await expect(row).toBeVisible({ timeout: 15000 })
  await expect(row).toHaveAttribute('aria-selected', 'true')
  expect(await win.getByRole('row').count()).toBeLessThan(100)
})

test('FB-07: full 10k selection stays virtual; input shortcuts do not select files', async ({ page }) => {
  const win = await openFiles(page)
  await win.getByRole('cell', { name: 'stress-10k', exact: true }).dblclick()
  await expect(win.getByText('10000 items', { exact: true })).toBeVisible()
  await win.locator('[role="row"][data-entry-id]').first().click()
  await page.keyboard.press('Control+a')
  await expect(win.getByText('10000 selected', { exact: true })).toBeVisible({ timeout: 15000 })
  expect(await win.getByRole('row').count()).toBeLessThan(100)
  await page.keyboard.press('Escape')
  await win.locator('[role="row"][data-entry-id]').first().click()
  await page.keyboard.press('F2')
  const prompt = page.getByTestId('name-prompt-dialog')
  await expect(prompt).toBeVisible()
  await prompt.getByRole('textbox').press('Control+a')
  await expect(win.getByText('10000 selected', { exact: true })).toHaveCount(0)
  await prompt.getByRole('button', { name: 'Cancel', exact: true }).click()
})

test('FB-08: dropped files upload to the target and conflicts keep both', async ({ page }) => {
  const win = await openFiles(page)
  await documents(page)
  await fixture(page, [{ id: 'existing-drop', name: 'drop.txt', path: '/home/Documents/drop.txt', sizeBytes: 0 }])
  const transfer = await page.evaluateHandle(() => { const data = new DataTransfer(); for (const name of ['drop.txt', 'second.txt', 'third.txt']) data.items.add(new File(['content'], name, { type: 'text/plain' })); return data })
  await win.locator('[data-pane="left"]').dispatchEvent('drop', { dataTransfer: transfer })
  await page.getByTestId('conflict-dialog').getByRole('button', { name: 'Keep both' }).click()
  await expect(win.getByTestId('transfer-success')).toHaveCount(3, { timeout: 15000 })
  await expect(win.getByRole('cell', { name: 'drop (2).txt', exact: true })).toBeVisible()
  await win.getByRole('button', { name: 'Collapse tasks' }).click()
  await expect(win.getByTestId('transfer-success')).toHaveCount(0)
  await win.getByRole('button', { name: 'Show 3 tasks' }).click()
  await expect(win.getByTestId('transfer-success')).toHaveCount(3)
})

test('FB-10/11: zero and unknown metadata, copy capability and sorting', async ({ page }) => {
  const win = await openFiles(page)
  await fixture(page, [{ id: 'zero', name: 'zero.txt', path: '/home/Documents/zero.txt', sizeBytes: 0 }, { id: 'unknown', name: 'unknown.txt', path: '/home/Documents/unknown.txt' }])
  await documents(page)
  await expect(win.getByRole('row').filter({ has: page.getByRole('cell', { name: 'zero.txt', exact: true }) })).toContainText('0 B')
  await win.getByRole('cell', { name: 'unknown.txt', exact: true }).click({ button: 'right' })
  await expect(page.getByRole('menuitem', { name: 'Copy files', exact: true })).toBeEnabled()
  await page.getByRole('menuitem', { name: 'Details', exact: true }).click()
  await win.getByRole('tab', { name: 'AI', exact: true }).click()
  await expect(win.getByText('AI processing status is unknown.', { exact: false })).toBeVisible()
  await win.getByRole('button', { name: 'Collapse sidebar', exact: true }).click()
  await win.getByRole('columnheader', { name: /Name/ }).getByRole('button').click()
  await expect(win.getByRole('columnheader', { name: /Name/ })).toHaveAttribute('aria-sort', 'descending')
})

test('FB-03: main controls fit 720/1024/1440 application widths', async ({ page }) => {
  const win = await openFiles(page)
  for (const width of [720, 1024, 1440]) {
    await win.evaluate((el, width) => { el.style.width = `${width + 2}px`; el.style.left = '0px' }, width)
    await expect.poll(() => win.getByTestId('filebrowser').evaluate((el) => Math.round(el.getBoundingClientRect().width))).toBe(width)
    const toolbar = win.getByTestId('files-toolbar')
    expect(await toolbar.evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
    for (const name of ['Search', 'More actions', 'Details', 'Upload']) {
      const bounds = await win.getByRole('button', { name, exact: true }).boundingBox()
      const container = await win.boundingBox()
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(container!.x + container!.width + 1)
    }
  }
})

test('FB-09: mobile opens content, returns to Documents, and moves with touch selection', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true })
  const page = await context.newPage()
  const errors: string[] = []
  page.on('pageerror', (err) => errors.push(err.message))
  await page.goto('/?scenario=normal&fbData=mock')
  await page.getByRole('button', { name: 'Files', exact: true }).tap()
  const files = page.getByTestId('filebrowser')
  await files.getByRole('button', { name: /Documents/ }).tap()
  await files.getByText('Kyoto Trip Plan.md', { exact: true }).tap()
  await expect(page.getByTestId('content-preview')).toHaveAttribute('data-status', 'ready', { timeout: 15000 })
  const previewBounds = await page.getByTestId('content-preview').boundingBox()
  const headerBounds = await page.getByLabel('Status bar').boundingBox()
  expect(previewBounds!.y).toBeGreaterThanOrEqual(headerBounds!.y + headerBounds!.height)
  await page.getByLabel('Status bar').getByRole('button', { name: 'Back', exact: true }).tap()
  await expect(files.getByText('Kyoto Trip Plan.md', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Status bar')).toContainText('Documents')
  const row = files.getByRole('button', { name: /Kyoto Trip Plan.md/ }).first()
  await row.dispatchEvent('pointerdown', { pointerId: 1, pointerType: 'touch', clientX: 100, clientY: 330 })
  await page.waitForTimeout(500)
  await row.dispatchEvent('pointerup', { pointerId: 1, pointerType: 'touch', clientX: 100, clientY: 330 })
  await expect(files.getByText('1 selected', { exact: true })).toBeVisible()
  await files.getByRole('button', { name: 'Move to', exact: true }).tap()
  const target = page.getByTestId('target-dialog')
  await target.getByRole('textbox', { name: 'Destination' }).fill('/home/Downloads')
  await target.getByRole('button', { name: 'Go', exact: true }).tap()
  await target.getByRole('button', { name: 'Move here' }).tap()
  await expect(files.getByTestId('batch-results')).toContainText('1 succeeded')
  await files.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).tap()
  await files.getByRole('button', { name: 'Places', exact: true }).tap()
  await files.getByRole('button', { name: 'AI Topics', exact: true }).tap()
  await files.getByRole('button', { name: /Kyoto trip · April/ }).tap()
  await expect(files.getByRole('button', { name: 'Upload', exact: true })).toHaveCount(0)
  const more = await files.getByRole('button', { name: 'More actions', exact: true }).first().boundingBox()
  expect(more!.width).toBeGreaterThanOrEqual(44)
  expect(more!.height).toBeGreaterThanOrEqual(44)
  expect(errors).toEqual([])
  await context.close()
})

test('FB-01/03: both split panes keep their selection and show the active pane', async ({ page }) => {
  const win = await openFiles(page)
  await win.getByRole('button', { name: 'Pictures', exact: true }).last().click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Send to Right', exact: true }).click()
  const left = win.locator('[data-pane="left"]')
  const right = win.locator('[data-pane="right"]')
  await left.getByRole('cell', { name: 'Documents', exact: true }).dblclick()
  await left.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true }).click()
  await right.getByRole('row').filter({ has: page.locator('[role="cell"]') }).first().click()
  await expect(right).toHaveAttribute('data-active', 'true')
  await expect(left.getByText('Selected: Kyoto Trip Plan.md')).toBeVisible()
  const selected = await right.locator('[aria-selected="true"]').getAttribute('data-entry-id')
  await left.getByRole('button', { name: 'Search', exact: true }).click()
  await left.getByPlaceholder(/Search across files/).fill('trip')
  await expect(left.getByTestId('search-hit').first()).toBeVisible()
  await expect(right.locator(`[data-entry-id="${selected}"]`)).toHaveAttribute('aria-selected', 'true')
})

test('FB-02: NFSP batches keep individual results, invalidate immediately and guard revisions', async ({ page }) => {
  await openFiles(page)
  const report = await page.evaluate(async () => {
    const { nfspClient } = await import('/src/app/filebrowser/data/nfsp/' + 'client.ts')
    const { registerNfspFolderOps } = await import('/src/app/filebrowser/data/nfsp/' + 'folderOps.ts')
    const { folderOps } = await import('/src/app/filebrowser/data/' + 'folderOps.ts')
    const { watchDfsPath } = await import('/src/app/filebrowser/data/nfsp/' + 'invalidation.ts')
    const calls: string[] = []
    const revisions: unknown[] = []
    const client = nfspClient()
    client.hello = async () => ({})
    client.stat = async (path: string, opts?: { name?: string }) => ({ ref: { type: 'live', node_id: opts?.name ?? path }, kind: opts?.name ? 'file' : 'dir', capabilities: { accepts_content: true }, revision: `revision:${path}` })
    client.delete = async (_path: string, name: string, options: unknown) => { calls.push(name); revisions.push(options); if (name === 'b') throw { code: 'PERMISSION_DENIED' } }
    const unwatch = watchDfsPath('/source', () => calls.push('invalidate'))
    registerNfspFolderOps()
    const entries = ['a','b','c'].map((name) => ({ id: name, name, path: `/source/${name}`, kind: 'document', modifiedAt: '2026-09-07T00:00:00Z' }))
    const results = await folderOps().deleteEntries(entries)
    const stale = await folderOps().deleteEntries([{ ...entries[0], id: 'replaced' }])
    client.stat = async () => { throw { code: 'PERMISSION_DENIED' } }
    let lookupError = ''
    try { await folderOps().nameExists('/source', 'a') } catch (err) { lookupError = (err as { code: string }).code }
    unwatch()
    return { calls, revisions, statuses: results.map((result: { status: string }) => result.status), stale: stale[0].error.code, lookupError }
  })
  expect(report.statuses).toEqual(['success', 'failed', 'success'])
  expect(report.calls).toEqual(['a', 'invalidate', 'b', 'c', 'invalidate'])
  expect(report.revisions).toEqual(Array(3).fill({ recursive: false, expectedRevision: 'revision:/source' }))
  expect(report.stale).toBe('STALE')
  expect(report.lookupError).toBe('PERMISSION_DENIED')
})

test('FB-07: cancelled full selection never starts deletion', async ({ page }) => {
  const win = await openFiles(page)
  await win.getByRole('cell', { name: 'stress-10k', exact: true }).dblclick()
  await win.locator('[role="row"][data-entry-id]').first().click()
  await page.keyboard.press('Control+a')
  await expect(win.getByText('Loading the full selection / locating file…')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.keyboard.press('Delete')
  await expect(page.getByTestId('delete-dialog')).toHaveCount(0)
  await expect(win.getByText('10000 selected', { exact: true })).toHaveCount(0)
})

test('FB-02: retry only failed items and cancellation preserves completed moves', async ({ page }) => {
  const win = await openFiles(page, '&fbSlowOps=1')
  await fixture(page, [
    { id: 'retry-a', name: 'retry-A.txt', path: '/home/Documents/retry-A.txt' },
    { id: 'retry-b', name: 'fail-once-B.txt', path: '/home/Documents/fail-once-B.txt' },
    { id: 'cancel-a', name: 'cancel-A.txt', path: '/home/Documents/cancel-A.txt' },
    { id: 'cancel-b', name: 'cancel-B.txt', path: '/home/Documents/cancel-B.txt' },
  ])
  await documents(page)
  for (const name of ['retry-A.txt', 'fail-once-B.txt']) await win.getByRole('checkbox', { name: `Select ${name}`, exact: true }).check()
  await win.locator('[data-pane="left"]').click({ position: { x: 10, y: 10 } })
  await page.keyboard.press('Control+x')
  await win.getByRole('button', { name: 'Pictures', exact: true }).last().click()
  await page.keyboard.press('Control+v')
  const results = win.getByTestId('batch-results')
  await expect(results).toContainText('1 succeeded · 1 failed')
  await results.getByRole('button', { name: 'Retry failed items' }).click()
  await expect(results).toContainText('2 succeeded · 0 failed')
  await expect(win.getByRole('cell', { name: 'retry-A.txt', exact: true })).toHaveCount(1)
  await results.getByRole('button', { name: 'Close', exact: true }).click()
  await win.getByRole('button', { name: 'Documents', exact: true }).last().click()
  for (const name of ['cancel-A.txt', 'cancel-B.txt']) await win.getByRole('checkbox', { name: `Select ${name}`, exact: true }).check()
  await win.locator('[data-pane="left"]').click({ position: { x: 10, y: 10 } })
  await page.keyboard.press('Control+x')
  await win.getByRole('button', { name: 'Pictures', exact: true }).last().click()
  await page.keyboard.press('Control+v')
  await expect(results).toContainText('1 succeeded')
  await results.getByRole('button', { name: 'Cancel remaining', exact: true }).click()
  await expect(results).toContainText('1 succeeded · 0 failed · 0 skipped · 1 cancelled')
  await expect(win.getByRole('cell', { name: 'cancel-A.txt', exact: true })).toBeVisible()
  await results.getByRole('button', { name: 'Close', exact: true }).click()
  await win.getByRole('button', { name: 'Documents', exact: true }).last().click()
  await expect(win.getByRole('cell', { name: 'cancel-B.txt', exact: true })).toBeVisible()
})

test('FB-08: skipped and cancelled uploads remain visible and retry checks conflicts again', async ({ page }) => {
  const win = await openFiles(page)
  await documents(page)
  await fixture(page, [
    { id: 'upload-existing-1', name: 'skip.txt', path: '/home/Documents/skip.txt' },
    { id: 'upload-existing-2', name: 'cancel.txt', path: '/home/Documents/cancel.txt' },
  ])
  const transfer = await page.evaluateHandle(() => { const data = new DataTransfer(); for (const name of ['skip.txt', 'cancel.txt', 'pending.txt']) data.items.add(new File(['hello'], name)); return data })
  await win.locator('[data-pane="left"]').dispatchEvent('drop', { dataTransfer: transfer })
  await page.getByTestId('conflict-dialog').getByRole('button', { name: 'Skip', exact: true }).click()
  await expect(page.getByTestId('conflict-dialog')).toContainText('cancel.txt')
  await page.getByTestId('conflict-dialog').getByRole('button', { name: 'Cancel remaining', exact: true }).click()
  await expect(win.getByTestId('transfer-skipped')).toHaveCount(1)
  await expect(win.getByTestId('transfer-cancelled')).toHaveCount(2)
  await win.getByTestId('transfer-cancelled').filter({ hasText: 'cancel.txt' }).getByRole('button', { name: 'Retry', exact: true }).click()
  await page.getByTestId('conflict-dialog').getByRole('button', { name: 'Keep both', exact: true }).click()
  await expect(win.getByTestId('transfer-success')).toContainText('cancel (2).txt', { timeout: 15000 })
})

test('FB-11: deep pins, column preferences, rename stem and extension feedback', async ({ page }) => {
  const win = await openFiles(page)
  await fixture(page, [{ id: 'pin-deep', name: 'Deep folder', path: '/home/Documents/Deep folder', kind: 'folder' }])
  await documents(page)
  await win.getByRole('cell', { name: 'Deep folder', exact: true }).dblclick()
  await win.getByRole('button', { name: 'Pin current folder', exact: true }).click()
  await win.locator('aside').first().getByRole('button', { name: 'Downloads', exact: true }).click()
  await win.getByRole('button', { name: '★ Deep folder', exact: true }).click()
  await expect(win.getByText('This folder is empty', { exact: true })).toBeVisible()
  await documents(page)
  await win.getByRole('button', { name: 'View mode', exact: true }).click()
  await page.getByRole('menuitem', { name: 'All columns (horizontal scroll)', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Comfortable rows', exact: true }).click()
  await page.keyboard.press('Escape')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('files.listPreferences')!))).toMatchObject({ fullColumns: true, density: 'comfortable' })
  await win.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true }).click()
  await page.keyboard.press('F2')
  const input = page.getByTestId('name-prompt-dialog').getByRole('textbox')
  await expect(input).toBeFocused()
  expect(await input.evaluate((el: HTMLInputElement) => el.value.slice(el.selectionStart!, el.selectionEnd!))).toBe('Kyoto Trip Plan')
  await input.fill('Kyoto Trip Plan.txt')
  await expect(page.getByText('Changing the extension may change which app opens this file.')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(win.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true })).toBeVisible()
})

test('FB-10: loading and read-only capabilities disable mutations consistently', async ({ page }) => {
  for (const [state, reason] of [['loading', 'Permissions are loading'], ['readonly', 'This location is read-only']]) {
    const win = await openFiles(page, `&fbCapabilities=${state}`)
    await documents(page)
    await win.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true }).click({ button: 'right' })
    const rename = page.getByRole('menuitem', { name: 'Rename…', exact: true })
    await expect(rename).toBeDisabled()
    await expect(rename).toContainText(reason)
    await page.keyboard.press('Escape')
    await page.keyboard.press('F2')
    await expect(page.getByTestId('name-prompt-dialog')).toHaveCount(0)
    await expect(win.getByRole('button', { name: 'Upload', exact: true })).toHaveCount(0)
    await expect(win.locator('p').filter({ hasText: reason })).toBeVisible()
  }
})

test('FB-08: dragging between panes moves files and adds collection references', async ({ page }) => {
  const win = await openFiles(page)
  await win.getByRole('button', { name: 'Pictures', exact: true }).last().click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Send to Right', exact: true }).click()
  const left = win.locator('[data-pane="left"]')
  const right = win.locator('[data-pane="right"]')
  await left.getByRole('cell', { name: 'Documents', exact: true }).dblclick()
  await left.getByRole('row').filter({ has: page.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true }) }).dragTo(right, { targetPosition: { x: 120, y: 400 } })
  await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
  await expect(right.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true })).toBeVisible()
  await expect(left.getByRole('cell', { name: 'Kyoto Trip Plan.md', exact: true })).toHaveCount(0)
  await win.getByTestId('batch-results').getByRole('button', { name: 'Close', exact: true }).click()
  await right.getByRole('button', { name: 'Places', exact: true }).click()
  await win.locator('aside').first().getByRole('button', { name: /Reading List/ }).click()
  await expect(right.getByText('6 items · originals stay in place')).toBeVisible()
  await left.getByRole('row').filter({ has: page.getByRole('cell', { name: 'Friend Contract Draft.pdf', exact: true }) }).dragTo(right, { targetPosition: { x: 120, y: 400 } })
  await expect(win.getByTestId('batch-results')).toContainText('1 succeeded')
  await expect(right.getByText('7 items · originals stay in place')).toBeVisible()
  await expect(left.getByRole('cell', { name: 'Friend Contract Draft.pdf', exact: true })).toBeVisible()
})
