import { expect, test } from '@playwright/test'

declare global {
  interface Window { __messageHubMockWorklogs: typeof import('../../../src/app/messagehub/mock/worklog').mockWorklogs }
}

test('agent messages open the turn work log, page upward, and open a created task', async ({ page }) => {
  await page.goto('/messagehub?sessionId=session-coder-task&messageId=msg-ct-10')
  const details = page.getByTestId('message-details-pane')
  await expect(details.getByTestId('detail-tab-worklog')).toHaveAttribute('aria-selected', 'true')
  const log = details.getByTestId('turn-worklog')
  await expect(log).toHaveAttribute('data-turn', '16')
  await expect(log).toHaveAttribute('data-session-id', 'ui-session-1')
  await expect(log.getByTestId('worklog-child')).toBeInViewport()
  await expect(log).toContainText('IN')
  await expect(log).toContainText('OUT')
  await expect(log.getByText('Turn started', { exact: true })).toHaveCount(0)
  await log.getByTestId('worklog-scroll').evaluate(el => { el.scrollTop = 0 })
  await expect(log.getByText('Turn started', { exact: true })).toBeVisible()
  await expect(log.getByText('Read message projection', { exact: true })).toBeVisible()
  await expect(log.getByTestId('worklog-older')).toHaveCount(0)
  expect(await log.getByTestId('worklog-scroll').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/messagehub-turn-worklog.png' })

  await log.getByTestId('worklog-child').click()
  await expect(log).toHaveAttribute('data-session-id', 'work-tests')
  await expect(log).toHaveAttribute('data-turn', '1')
  await expect(log.getByText('Turn ended', { exact: true })).toBeVisible()
  await log.getByTestId('worklog-task-details').click()
  await expect(details.getByTestId('detail-task-id')).toHaveText('task-turn-checklist.tests')
  await details.getByTestId('worklog-back').click()
  await expect(log).toHaveAttribute('data-session-id', 'work-tests')
  await details.getByTestId('worklog-back').click()
  await expect(log).toHaveAttribute('data-session-id', 'ui-session-1')
  await details.getByTestId('detail-tab-message').click()
  await expect(details.getByTestId('detail-message-id')).toHaveText('msg-ct-10')
})

test('work logs fit a phone and a completed turn stays bound after reload', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/messagehub?sessionId=session-coder-task')
  const bubble = page.getByTestId('conversation-history').locator('[data-message-id="msg-ct-2"]')
  await bubble.getByText('3 failures', { exact: false }).first().click()
  const log = page.getByTestId('turn-worklog')
  await expect(log).toHaveAttribute('data-turn', '12')
  await expect(log.getByText('Turn ended', { exact: true })).toBeVisible()
  expect(await log.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/messagehub-turn-worklog-mobile.png' })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/messagehub?sessionId=session-coder-task&messageId=msg-ct-2')
  await expect(log).toHaveAttribute('data-turn', '12')
  await page.reload()
  await expect(log).toHaveAttribute('data-turn', '12')
  await expect(log.getByText('Turn ended', { exact: true })).toBeVisible()
})

test('live entries follow the bottom, preserve reading position, recover, and stop polling after completion', async ({ page }) => {
  await page.goto('/messagehub?sessionId=session-coder-task&messageId=msg-ct-10')
  const log = page.getByTestId('turn-worklog')
  const scroll = log.getByTestId('worklog-scroll')
  await expect(log.getByTestId('worklog-child')).toBeInViewport()
  await page.evaluate(() => window.__messageHubMockWorklogs.append('ui-session-1', 16, { t: 'assistant_message', run_id: 'run-16', assistant: 'New progress at the bottom' }))
  await expect(log.getByText('New progress at the bottom')).toBeInViewport({ timeout: 10_000 })
  await scroll.evaluate(el => { el.scrollTop = el.scrollHeight / 2 })
  const position = await scroll.evaluate(el => el.scrollTop)
  await page.evaluate(() => window.__messageHubMockWorklogs.append('ui-session-1', 16, { t: 'assistant_message', run_id: 'run-16', assistant: 'Progress while reading earlier entries' }))
  await expect(log.getByText('Progress while reading earlier entries')).toBeAttached({ timeout: 10_000 })
  expect(Math.abs(await scroll.evaluate(el => el.scrollTop) - position)).toBeLessThan(4)
  await page.evaluate(() => { window.__messageHubMockWorklogs.offline = true })
  await expect(log.getByRole('alert')).toContainText('Could not read', { timeout: 10_000 })
  await page.evaluate(() => { window.__messageHubMockWorklogs.offline = false })
  await log.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(log.getByRole('alert')).toHaveCount(0)
  await log.getByRole('button', { name: 'Latest activity', exact: true }).click()
  await page.evaluate(() => window.__messageHubMockWorklogs.append('ui-session-1', 16, { t: 'turn_ended', run_id: 'run-16', status: 'stopped', at_ms: Date.now() }, true))
  await expect(log.getByText('Turn ended', { exact: true })).toBeInViewport({ timeout: 10_000 })
  await expect(log.getByText('Stopped', { exact: true })).toBeVisible()
  const reads = await page.evaluate(() => window.__messageHubMockWorklogs.reads)
  await page.waitForTimeout(3000)
  expect(await page.evaluate(() => window.__messageHubMockWorklogs.reads)).toBe(reads)
})
