[package]
name = "node_daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
simplelog = "*"
thiserror = "*"
tokio = { version = "*", features = ["full"] }