[package]
name = "etcd_client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "*", features = ["blocking", "json"]}
etcd-rs = "*"
tokio = { version = "*", features = ["full"] }
serde_json="*"
log = "*"
