[package]
name = "msg_queue"
version = "0.5.0"
edition = "2021"
authors = ["BuckyOS DAO","@waterflier"]

[dependencies]
async-nats = "*"
async-trait = "*"
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
log = "*"
anyhow = "*"
thiserror = "*"
uuid = { version = "*", features = ["v4", "serde"] }
futures = "*"
kRPC = { path = "../kRPC" }
buckyos-kit = { path = "../../components/buckyos-kit" }
buckyos-api = { path = "../../kernel/buckyos-api" }
cyfs-warp = { path = "../../cyfs_gateway/cyfs-warp" }
cyfs-gateway-lib = { path = "../../cyfs_gateway/cyfs-gateway-lib" }

[dev-dependencies]
mockall = "*"
tokio-test = "*"
