[package]
name = "msg_queue"
version = "0.5.0"
edition = "2021"

[dependencies]
async-nats = "*"
async-trait = "*"
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
anyhow = "*"
thiserror = "*"
tracing = "*"
uuid = { version = "*", features = ["v4", "serde"] }
futures = "*"

[dev-dependencies]
mockall = "*"
tokio-test = "*"
