[package]
name = "package_server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.10"
clap = "3.1.6"
hex = "0.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9"
simplelog = "0.11"
tide = "0.16"