#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: root
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+1ahNCB868koYLULmy7IG/HEz5j41oFO7Pe76tho4K lzc@buckydev02
    #buckyos2025
    passwd: "$6$rounds=4096$vumjqMkVLNRXUvJw$iaiDsWKCGKgjeC7sp.PpGw6BOJkUaRCQ.XInFhfq39DEp6lRNswnyF4gVrE9UW7qqIF0zvQisY/OwglgPO2oc1"
    chpasswd:
    expire: false
    ssh_pwauth: true
    disable_root: false

package_update: true   # 更新包列表
package_upgrade: true  # 升级已安装的包

# 安装指定的软件包
packages:
  - docker.io
  - curl
  - wget

# 运行初始化命令
runcmd:
  - pip3 install docker --break-system-packages

