[package]
name = "etcd_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
etcd_client = {path = "../etcd_client"}
serde = "1.0.198"
serde_json = "1.0.116"
tokio = { version = "1.37.0"}
clap = "4.5.4"
sfo-result = "0.1.1"
