//! `<sid>/.runtime/bin` — the Session Bin layer, first on PATH (§7.1).
//!
//! Content: tool-plan tombstones (stubs that shadow blocked tools) and
//! session helper scripts (e.g. the `agent-session` CLI wrapper used to
//! declare activity / perceptions from inside `exec`). Agent tools stay a
//! separate PATH layer (`<agent_root>/tools`), tombstones shadow them.
//!
//! Preparation is idempotent and repairable: the expected set is computed,
//! every entry is (re)written through an atomic replace, stale entries are
//! removed, and a manifest (`.manifest.json`, written last) records the
//! expected content hashes. `verify` checks the manifest against the files;
//! a half-prepared directory (crash in the middle) fails verification and
//! the next `prepare` repairs it.

use std::collections::{BTreeMap, HashSet};
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::error::{OpenDanError, Result};
use crate::fsutil;

pub const MANIFEST: &str = ".manifest.json";

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PlanMode {
    #[default]
    Deny,
    Allow,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolPlanEntry {
    pub name: String,
    #[serde(default)]
    pub reason: String,
}

/// `<agent_root>/tool_plans/<name>.toml` (same schema as opendan).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(default)]
pub struct ToolPlan {
    pub mode: PlanMode,
    pub deny: Vec<ToolPlanEntry>,
    pub allow: Vec<ToolPlanEntry>,
}

impl ToolPlan {
    pub fn load(agent_root: &Path, name: &str) -> Result<Option<ToolPlan>> {
        let path = agent_root.join("tool_plans").join(format!("{name}.toml"));
        match std::fs::read_to_string(&path) {
            Ok(s) => toml::from_str(&s)
                .map(Some)
                .map_err(|e| OpenDanError::json(&path, e)),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
            Err(e) => Err(OpenDanError::io(&path, e)),
        }
    }
}

/// What the Session Bin must contain.
#[derive(Debug, Clone, Default)]
pub struct BinPlan {
    pub tool_plan_name: Option<String>,
    pub tool_plan: Option<ToolPlan>,
    /// Executable providing the `agent-session` helper CLI (wrapped).
    pub session_cli: Option<PathBuf>,
    /// Extra fixed scripts `name → content`.
    pub scripts: BTreeMap<String, String>,
    /// Directories whose executables form the tool universe for tombstones.
    pub universe_dirs: Vec<PathBuf>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct BinManifest {
    /// name → sha256 of the content.
    pub entries: BTreeMap<String, String>,
    #[serde(default)]
    pub tool_plan: Option<String>,
    #[serde(default)]
    pub prepared_at_ms: u64,
}

fn sha(content: &[u8]) -> String {
    hex::encode(Sha256::digest(content))
}

fn is_executable(meta: &std::fs::Metadata) -> bool {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        meta.permissions().mode() & 0o111 != 0
    }
    #[cfg(not(unix))]
    {
        let _ = meta;
        true
    }
}

fn scan_universe(dirs: &[PathBuf]) -> HashSet<String> {
    let mut out = HashSet::new();
    for d in dirs {
        let Ok(rd) = std::fs::read_dir(d) else {
            continue;
        };
        for e in rd.flatten() {
            if let Ok(meta) = e.metadata() {
                if meta.is_file() && is_executable(&meta) {
                    if let Some(n) = e.file_name().to_str() {
                        out.insert(n.to_string());
                    }
                }
            }
        }
    }
    out
}

fn tombstone_script(tool: &str, reason: &str, plan: &str) -> String {
    let esc = |s: &str| s.replace('\\', "\\\\").replace('"', "\\\"").replace('\'', "");
    format!(
        "#!/bin/sh\n# generated by libopendan (tool plan tombstone)\n\
         echo '{{\"blocked_by\":\"tool_plan\",\"tool\":\"{t}\",\"reason\":\"{r}\",\"plan\":\"{p}\"}}' >&2\n\
         echo '{t} is blocked by tool plan: {r}' >&2\n\
         exit 127\n",
        t = esc(tool),
        r = esc(reason),
        p = esc(plan)
    )
}

fn cli_wrapper(cli: &Path) -> String {
    format!(
        "#!/bin/sh\n# generated by libopendan: session helper CLI\nexec \"{}\" \"$@\"\n",
        cli.display().to_string().replace('"', "\\\"")
    )
}

/// Compute the expected entries of the Session Bin.
pub fn expected_entries(plan: &BinPlan, path_env: Option<&str>) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    if let Some(cli) = &plan.session_cli {
        out.insert("agent-session".to_string(), cli_wrapper(cli));
    }
    for (n, c) in &plan.scripts {
        out.insert(n.clone(), c.clone());
    }
    if let (Some(name), Some(tp)) = (&plan.tool_plan_name, &plan.tool_plan) {
        let universe = scan_universe(&plan.universe_dirs);
        match tp.mode {
            PlanMode::Deny => {
                // Deny lists shadow the name wherever it would be found on
                // PATH (agent / runtime layers and the system PATH).
                let mut on_path = universe.clone();
                if let Some(p) = path_env {
                    let dirs: Vec<PathBuf> = p.split(':').map(PathBuf::from).collect();
                    on_path.extend(scan_universe(&dirs));
                }
                for e in &tp.deny {
                    let n = e.name.trim();
                    if n.is_empty() || !on_path.contains(n) {
                        continue;
                    }
                    let reason = if e.reason.trim().is_empty() {
                        format!("blocked by tool plan `{name}`")
                    } else {
                        e.reason.clone()
                    };
                    out.insert(n.to_string(), tombstone_script(n, &reason, name));
                }
            }
            PlanMode::Allow => {
                let allowed: HashSet<&str> =
                    tp.allow.iter().map(|e| e.name.as_str()).collect();
                for n in universe {
                    if allowed.contains(n.as_str()) {
                        continue;
                    }
                    let reason = format!("not in allow list of tool plan `{name}`");
                    out.insert(n.clone(), tombstone_script(&n, &reason, name));
                }
            }
        }
    }
    out
}

#[cfg(unix)]
fn set_exec(path: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut p = std::fs::metadata(path)
        .map_err(|e| OpenDanError::io(path, e))?
        .permissions();
    p.set_mode(0o755);
    std::fs::set_permissions(path, p).map_err(|e| OpenDanError::io(path, e))
}

#[cfg(not(unix))]
fn set_exec(_path: &Path) -> Result<()> {
    Ok(())
}

/// Idempotently (re)build the Session Bin; the manifest is written last.
pub fn prepare(bin_dir: &Path, plan: &BinPlan) -> Result<BinManifest> {
    std::fs::create_dir_all(bin_dir).map_err(|e| OpenDanError::io(bin_dir, e))?;
    let path_env = std::env::var("PATH").ok();
    let expected = expected_entries(plan, path_env.as_deref());
    // Invalidate the manifest first: a crash mid-way must fail verification.
    let manifest_path = bin_dir.join(MANIFEST);
    let _ = std::fs::remove_file(&manifest_path);
    for (name, content) in &expected {
        let path = bin_dir.join(name);
        let tmp = bin_dir.join(format!(".{name}.tmp-{}", uuid::Uuid::new_v4().simple()));
        std::fs::write(&tmp, content.as_bytes()).map_err(|e| OpenDanError::io(&tmp, e))?;
        set_exec(&tmp)?;
        std::fs::rename(&tmp, &path).map_err(|e| OpenDanError::io(&path, e))?;
    }
    // Remove entries we generated earlier that are no longer expected, and
    // leftovers of interrupted writes.
    if let Ok(rd) = std::fs::read_dir(bin_dir) {
        for e in rd.flatten() {
            let n = e.file_name().to_string_lossy().to_string();
            if n == MANIFEST {
                continue;
            }
            if n.starts_with('.') || !expected.contains_key(&n) {
                let _ = std::fs::remove_file(e.path());
            }
        }
    }
    let manifest = BinManifest {
        entries: expected
            .iter()
            .map(|(n, c)| (n.clone(), sha(c.as_bytes())))
            .collect(),
        tool_plan: plan.tool_plan_name.clone(),
        prepared_at_ms: crate::now_ms(),
    };
    fsutil::atomic_replace_json(&manifest_path, &manifest)?;
    Ok(manifest)
}

/// Verify the Session Bin against its manifest and the expected plan.
pub fn verify(bin_dir: &Path, plan: &BinPlan) -> Result<()> {
    let manifest: BinManifest = fsutil::read_json_opt(&bin_dir.join(MANIFEST))?
        .ok_or_else(|| OpenDanError::Bind("session bin is not prepared (no manifest)".into()))?;
    let path_env = std::env::var("PATH").ok();
    let expected = expected_entries(plan, path_env.as_deref());
    for (name, content) in &expected {
        if manifest.entries.get(name) != Some(&sha(content.as_bytes())) {
            return Err(OpenDanError::Bind(format!(
                "session bin entry `{name}` is missing from the manifest or outdated"
            )));
        }
    }
    for (name, digest) in &manifest.entries {
        let path = bin_dir.join(name);
        let data = std::fs::read(&path)
            .map_err(|_| OpenDanError::Bind(format!("session bin entry `{name}` is missing")))?;
        if &sha(&data) != digest {
            return Err(OpenDanError::Bind(format!(
                "session bin entry `{name}` content does not match the manifest"
            )));
        }
        let meta = std::fs::metadata(&path).map_err(|e| OpenDanError::io(&path, e))?;
        if !is_executable(&meta) {
            return Err(OpenDanError::Bind(format!(
                "session bin entry `{name}` is not executable"
            )));
        }
    }
    Ok(())
}
