const en = {
  normalizeEol: 'Saving will normalize mixed line endings to the selected format.',
  title: 'Text Editor', files: 'Files', outline: 'Outline', noOutline: 'No outline for this file', new: 'New file', open: 'Open file', save: 'Save', saveAs: 'Save as…', close: 'Close tab', menu: 'Actions', single: 'Single pane', columns: 'Split columns', rows: 'Split rows', quick: 'Quick open', find: 'Find / Replace', goto: 'Go to line', settings: 'Settings', recovery: 'Recovery', buffers: 'Unsaved changes', recent: 'Recent files', empty: 'Open a file or start writing.', reload: 'Reload (archive my changes)', overwrite: 'Overwrite (archive disk version)', overwriteCopy: 'Overwrite and keep conflict copy', recreate: 'Recreate file', retry: 'Retry', keep: 'Keep changes', discard: 'Discard (archive changes)', cancel: 'Cancel', closeChanges: 'Save changes before closing?',
  'external-modified': 'The file changed on disk. Choose which version to keep.', deleted: 'The original file was deleted.', 'lease-busy': 'Another client is writing this file.', 'copy-failed': 'Cannot create a conflict copy here. The disk version is in Recovery. Overwrite only?',
  restore: 'Restore', disk: 'Open disk version', remove: 'Delete', clear: 'Clear recovery', confirmDelete: 'Permanently delete these recovery files?', 'in-sync': 'Saved', changed: 'Disk changed', saving: 'Saving…', error: 'Save failed', saved: 'Saved', synced: 'Unsaved (synced)', unsynced: 'Unsaved (not synced to server)', readonly: 'Read only', edit: 'Enable editing', utf8: 'Convert to UTF-8 and edit', encoding: 'Encoding', language: 'Language', whitespace: 'Show whitespace', fontSize: 'Font size', tabSize: 'Tab size', insertSpaces: 'Insert spaces', wordWrap: 'Word wrap', lineNumbers: 'Line numbers', autoReloadClean: 'Reload unchanged files automatically', restoreSession: 'Restore workspace', closeKeepsChanges: 'Keep changes without asking on close', trimTrailingWhitespaceOnSave: 'Trim trailing whitespace on save', ensureFinalNewline: 'Ensure final newline', discardedDays: 'Discarded changes: retention days', takenOverDays: 'Taken-over changes: retention days', preview: 'Open in Preview', path: 'Location', filename: 'File name', parent: 'Parent folder', choose: 'Choose', login: 'Sign in', loginPopup: 'Sign in in another tab', loginNeeded: 'Sign in to access your files.', connecting: 'Connecting…', sessionLost: 'Your sign-in has expired. Changes stay on this device until you sign in again.', later: 'Later', 'binary': 'This is not a text file.', 'too-large': 'Files larger than 16 MiB cannot be edited.', 'buffer-in-use': 'This buffer is being edited in another window.', large: 'Large file mode', mixed: 'Mixed line endings', emptyRecovery: 'No recovery files.', emptyBuffers: 'No unsaved changes.', select: 'Select file', savedRecovery: 'Archived in Recovery', deleteBuffer: 'Discard buffer', download: 'Download', reopenEncoding: 'Reopen with encoding', selected: 'selected', line: 'Ln', column: 'Col', auto: 'Automatic', on: 'On', off: 'Off', plain: 'Plain text', newWindow: 'New window'
}
const zh: Record<keyof typeof en, string> = {
  normalizeEol: '保存时会将混合换行统一为当前选择的格式。',
  title: '文本编辑器', files: '文件', outline: '大纲', noOutline: '此文件类型没有大纲', new: '新建文件', open: '打开文件', save: '保存', saveAs: '另存为…', close: '关闭标签', menu: '操作', single: '单栏', columns: '双列分屏', rows: '双行分屏', quick: '快速打开', find: '查找 / 替换', goto: '跳转到行', settings: '设置', recovery: '恢复区', buffers: '未保存的修改', recent: '最近文件', empty: '打开文件，或开始写作。', reload: '重新加载（先存档我的修改）', overwrite: '覆盖（磁盘版本存入恢复区）', overwriteCopy: '覆盖并保留冲突副本', recreate: '在原路径重新创建', retry: '重试', keep: '保留修改', discard: '不保存（修改存入恢复区）', cancel: '取消', closeChanges: '关闭前保存修改？',
  'external-modified': '磁盘上的文件已更改。请选择要保留的版本。', deleted: '原文件已被删除。', 'lease-busy': '另一个客户端正在写入此文件。', 'copy-failed': '无法在原目录创建冲突副本。磁盘版本已存入恢复区，是否仅覆盖？', restore: '恢复', disk: '打开磁盘版本', remove: '删除', clear: '清空恢复区', confirmDelete: '永久删除这些恢复文件？', 'in-sync': '已保存', changed: '磁盘已更改', saving: '保存中…', error: '保存失败', saved: '保存成功', synced: '未保存（已同步）', unsynced: '未保存（尚未同步到服务器）', readonly: '只读', edit: '启用编辑', utf8: '转换为 UTF-8 并编辑', encoding: '编码', language: '语言', whitespace: '显示空白字符', fontSize: '字号', tabSize: '缩进宽度', insertSpaces: '使用空格缩进', wordWrap: '自动换行', lineNumbers: '显示行号', autoReloadClean: '自动重新加载未修改文件', restoreSession: '恢复工作区', closeKeepsChanges: '关闭时不再询问，保留修改', trimTrailingWhitespaceOnSave: '保存时去除行尾空白', ensureFinalNewline: '保存时确保末尾换行', discardedDays: '放弃的修改保留天数', takenOverDays: '接管的修改保留天数', preview: '在 Preview 中打开', path: '位置', filename: '文件名', parent: '上级目录', choose: '选择', login: '登录', loginPopup: '在新标签页登录', loginNeeded: '登录后访问文件。', connecting: '正在连接…', sessionLost: '登录已失效，重新登录前修改只保留在本机。', later: '稍后', binary: '这不是文本文件。', 'too-large': '无法编辑超过 16 MiB 的文件。', 'buffer-in-use': '此缓冲区正在另一个窗口中编辑。', large: '大文件模式', mixed: '混合换行', emptyRecovery: '恢复区为空。', emptyBuffers: '没有未保存的修改。', select: '选择文件', savedRecovery: '已存入恢复区', deleteBuffer: '丢弃缓冲区', download: '下载', reopenEncoding: '以其他编码重新打开', selected: '已选择', line: '行', column: '列', auto: '自动', on: '开启', off: '关闭', plain: '纯文本', newWindow: '新窗口'
}
export const translate = (locale: string, key: string): string => (locale.startsWith('zh') ? zh : en)[key as keyof typeof en] ?? key
