#!/usr/bin/python3

import os
import sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts import util
current_dir = os.path.dirname(os.path.abspath(__file__))

util.nohup_start(f"sudo apt-get install -y samba")
