export const ENTITY_LIST_DEFAULT_WIDTH = 340
export const ENTITY_LIST_MIN_WIDTH = 300
export const ENTITY_LIST_MAX_WIDTH = 520
export const ENTITY_LIST_COLLAPSED_WIDTH = 68

export const SESSION_SIDEBAR_DEFAULT_WIDTH = 280
export const SESSION_SIDEBAR_MIN_WIDTH = 240
export const SESSION_SIDEBAR_MAX_WIDTH = ENTITY_LIST_MAX_WIDTH

export const PANEL_SPLITTER_WIDTH = 6

export const DETAILS_PANEL_WIDTH = 320
export const CONVERSATION_MIN_READING_WIDTH = 480
