name: Build All

on:
  workflow_dispatch:
    inputs:
      enable_tests:
        description: 'Enable cargo tests during build'
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      enable_tests:
        description: 'Enable cargo tests during build'
        required: false
        type: boolean
        default: false

jobs:
  build-windows:
    strategy:
      matrix:
        arch: ["x86_64"]
    uses: ./.github/workflows/build-windows.yml
    with:
      arch: ${{ matrix.arch }}
      enable_tests: ${{inputs.enable_tests}}
    secrets: inherit
  build-linux:
    strategy:
      matrix:
        arch: ["x86_64", "aarch64"]
    uses: ./.github/workflows/build-linux.yml
    with:
      arch: ${{ matrix.arch }}
      enable_tests: ${{inputs.enable_tests}}
    secrets: inherit
  build-macos:
    strategy:
      matrix:
        arch: ["x86_64", "aarch64"]
    uses: ./.github/workflows/build-macos.yml
    with:
      arch: ${{ matrix.arch }}
      enable_tests: ${{inputs.enable_tests}}
    secrets: inherit