name: Build Buckyos MacOS Components
on: 
    workflow_call:
        inputs:
            arch:
                required: true
                type: string
            enable_tests:
                required: false
                type: boolean
                default: false

jobs:
  build:
    name: build
    runs-on: ${{ inputs.arch == 'aarch64' && 'macos-15' || 'macos-15-intel' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "latest"
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{inputs.arch}}-apple-darwin
    - name: cargo test
      working-directory: ./src
      if: ${{inputs.enable_tests == 'true'}}
      run: sudo cargo test -- --test-threads=1
    - name: install buckyos devkit
      run: pip install "buckyos-devkit @ git+https://github.com/buckyos/buckyos-devkit.git"
    - name: build buckyos
      working-directory: ./src
      run: sudo buckyos-build
    - name: Tar Rootfs
      run: 
        cd ./src/rootfs && tar -cvf ../../rootfs.tar .
    - name: Prepare tools
      run: 
        sudo mkdir -p tools && sudo chmod 777 tools && sudo cp ./src/rootfs/bin/buckycli/buckycli ./tools/ 
    - name: Get Version
      id: get_version
      run: |
        version=$("./src/rootfs/bin/node-daemon/node_daemon" --version)

        full_version=$(printf '%s\n' "$version" | sed -En 's/^[^0-9]*([0-9]+(\.[0-9]+)*\+build[^[:space:]]+).*/\1/p')
        echo "full_version=$full_version" >> "$GITHUB_OUTPUT"

        short_version=$(printf '%s\n' "$version" | sed -En 's/^[^0-9]*([0-9]+(\.[0-9]+)*\+build[0-9]+).*/\1/p')
        echo "short_version=$short_version" >> "$GITHUB_OUTPUT"
    - name: Upload tools
      uses: actions/upload-artifact@v6
      with:
        name: buckyos-tools-apple-${{inputs.arch == 'x86_64' && 'amd64' || 'aarch64'}}-${{steps.get_version.outputs.short_version}}
        path: tools
        if-no-files-found: error
    - name: Upload
      id: upload
      uses: actions/upload-artifact@v6
      with:
        name: buckyos-apple-${{inputs.arch == 'x86_64' && 'amd64' || 'aarch64'}}-${{steps.get_version.outputs.short_version}}
        path: rootfs.tar
        if-no-files-found: error
    - name: Report Upload Urls
      run: |
        npm install @buckyos/test-server-client
        npx test-server-client seturl buckyos ${{steps.get_version.outputs.short_version}} macos ${{inputs.arch}} ${{steps.upload.outputs.artifact-url}} ${{github.sha}}
      env:
        USERNAME: ${{ secrets.TEST_SERVER_USERNAME }}
        PRIVATE_KEY: ${{ secrets.TEST_SERVER_PRIVATE_KEY }}
        ENDPOINT: "https://buckyos.ai"
