name: Build and Pack Buckyos Installer

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        type: string

jobs:
    build:
        uses: ./.github/workflows/build-all.yml
        with:
            version: ${{ inputs.version }}
    pack:
        needs: build
        uses: ./.github/workflows/pack_installer.yml
        with:
            version: ${{ inputs.version }}
            build_time: ${{ needs.build.outputs.build_time }}
            run_id: ${{ github.run_id }}