name: Build Buckyos Windows Components
on: 
    workflow_call:
        inputs:
            arch:
                required: true
                type: string
            enable_tests:
                required: false
                type: boolean
                default: false

jobs:
  build:
    name: build
    runs-on: ${{ inputs.arch == 'aarch64' && 'windows-11-arm' || 'windows-2025' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "latest"
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{inputs.arch}}-pc-windows-msvc
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11' 
    - name: cargo test
      working-directory: ./src
      if: ${{inputs.enable_tests == true}}
      run: cargo test -- --test-threads=1
    - name: install buckyos devkit
      run: pip install "buckyos-devkit @ git+https://github.com/buckyos/buckyos-devkit.git"
    - name: build buckyos
      working-directory: ./src
      run: buckyos-build
      env:
        PYTHONIOENCODING: 'utf-8'
        PYTHONLEGACYWINDOWSSTDIO: "utf-8"
    - name: Get Version
      id: get_version
      shell: pwsh
      run: |
        $version = (& './src/rootfs/bin/node-daemon/node_daemon' --version)

        if ($version -match '\d+(?:\.\d+)*\+build\S+') {
            $full_version = $matches[0]
            Add-Content -Path $env:GITHUB_OUTPUT -Value "full_version=$full_version"
        }

        if ($version -match '\d+(?:\.\d+)*\+build\d+') {
            $short_version = $matches[0]
            Add-Content -Path $env:GITHUB_OUTPUT -Value "short_version=$short_version"
        }
    - name: Prepare tools
      run: |
        mkdir tools
        copy src\rootfs\bin\buckycli\buckycli.exe tools
    - name: Upload tools
      uses: actions/upload-artifact@v6
      with:
        name: buckyos-tools-windows-${{inputs.arch == 'x86_64' && 'amd64' || 'aarch64'}}-${{steps.get_version.outputs.short_version}}
        path: tools
        if-no-files-found: error
    - name: Upload
      id: upload
      uses: actions/upload-artifact@v6
      with:
        name: buckyos-windows-${{inputs.arch == 'x86_64' && 'amd64' || 'aarch64'}}-${{steps.get_version.outputs.short_version}}
        path: src/rootfs
        if-no-files-found: error
    - name: Report Upload Urls
      run: |
        npm install @buckyos/test-server-client
        npx test-server-client seturl buckyos ${{steps.get_version.outputs.short_version}} windows ${{inputs.arch}} ${{steps.upload.outputs.artifact-url}} ${{github.sha}}
      env:
        USERNAME: ${{ secrets.TEST_SERVER_USERNAME }}
        PRIVATE_KEY: ${{ secrets.TEST_SERVER_PRIVATE_KEY }}
        ENDPOINT: "https://buckyos.ai"
